// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "sample_real"
#define AUTOTB_TVIN_sample_real  "../tv/cdatafile/c.dft.autotvin_sample_real.dat"
#define AUTOTB_TVOUT_sample_real  "../tv/cdatafile/c.dft.autotvout_sample_real.dat"
// wrapc file define: "sample_imag"
#define AUTOTB_TVIN_sample_imag  "../tv/cdatafile/c.dft.autotvin_sample_imag.dat"
#define AUTOTB_TVOUT_sample_imag  "../tv/cdatafile/c.dft.autotvout_sample_imag.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "sample_real"
#define AUTOTB_TVOUT_PC_sample_real  "../tv/rtldatafile/rtl.dft.autotvout_sample_real.dat"
// tvout file define: "sample_imag"
#define AUTOTB_TVOUT_PC_sample_imag  "../tv/rtldatafile/rtl.dft.autotvout_sample_imag.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			sample_real_depth = 0;
			sample_imag_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{sample_real " << sample_real_depth << "}\n";
			total_list << "{sample_imag " << sample_imag_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int sample_real_depth;
		int sample_imag_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern void dft (
float sample_real[256],
float sample_imag[256]);

void AESL_WRAP_dft (
float sample_real[256],
float sample_imag[256])
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "sample_real"
		aesl_fh.read(AUTOTB_TVOUT_PC_sample_real, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_sample_real, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_sample_real, AESL_token); // data

			sc_bv<32> *sample_real_pc_buffer = new sc_bv<32>[256];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'sample_real', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'sample_real', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					sample_real_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_sample_real, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_sample_real))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: sample_real
				{
					// bitslice(31, 0)
					// {
						// celement: sample_real(31, 0)
						// {
							sc_lv<32>* sample_real_lv0_0_255_1 = new sc_lv<32>[256];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: sample_real(31, 0)
						{
							// carray: (0) => (255) @ (1)
							for (int i_0 = 0; i_0 <= 255; i_0 += 1)
							{
								if (&(sample_real[0]) != NULL) // check the null address if the c port is array or others
								{
									sample_real_lv0_0_255_1[hls_map_index].range(31, 0) = sc_bv<32>(sample_real_pc_buffer[hls_map_index].range(31, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: sample_real(31, 0)
						{
							// carray: (0) => (255) @ (1)
							for (int i_0 = 0; i_0 <= 255; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : sample_real[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : sample_real[0]
								// output_left_conversion : *(int*)&sample_real[i_0]
								// output_type_conversion : (sample_real_lv0_0_255_1[hls_map_index]).to_uint64()
								if (&(sample_real[0]) != NULL) // check the null address if the c port is array or others
								{
									*(int*)&sample_real[i_0] = (sample_real_lv0_0_255_1[hls_map_index]).to_uint64();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] sample_real_pc_buffer;
		}

		// output port post check: "sample_imag"
		aesl_fh.read(AUTOTB_TVOUT_PC_sample_imag, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_sample_imag, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_sample_imag, AESL_token); // data

			sc_bv<32> *sample_imag_pc_buffer = new sc_bv<32>[256];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'sample_imag', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'sample_imag', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					sample_imag_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_sample_imag, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_sample_imag))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: sample_imag
				{
					// bitslice(31, 0)
					// {
						// celement: sample_imag(31, 0)
						// {
							sc_lv<32>* sample_imag_lv0_0_255_1 = new sc_lv<32>[256];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: sample_imag(31, 0)
						{
							// carray: (0) => (255) @ (1)
							for (int i_0 = 0; i_0 <= 255; i_0 += 1)
							{
								if (&(sample_imag[0]) != NULL) // check the null address if the c port is array or others
								{
									sample_imag_lv0_0_255_1[hls_map_index].range(31, 0) = sc_bv<32>(sample_imag_pc_buffer[hls_map_index].range(31, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: sample_imag(31, 0)
						{
							// carray: (0) => (255) @ (1)
							for (int i_0 = 0; i_0 <= 255; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : sample_imag[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : sample_imag[0]
								// output_left_conversion : *(int*)&sample_imag[i_0]
								// output_type_conversion : (sample_imag_lv0_0_255_1[hls_map_index]).to_uint64()
								if (&(sample_imag[0]) != NULL) // check the null address if the c port is array or others
								{
									*(int*)&sample_imag[i_0] = (sample_imag_lv0_0_255_1[hls_map_index]).to_uint64();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] sample_imag_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "sample_real"
		char* tvin_sample_real = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_sample_real);
		char* tvout_sample_real = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_sample_real);

		// "sample_imag"
		char* tvin_sample_imag = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_sample_imag);
		char* tvout_sample_imag = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_sample_imag);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_sample_real, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_sample_real, tvin_sample_real);

		sc_bv<32>* sample_real_tvin_wrapc_buffer = new sc_bv<32>[256];

		// RTL Name: sample_real
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: sample_real(31, 0)
				{
					// carray: (0) => (255) @ (1)
					for (int i_0 = 0; i_0 <= 255; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : sample_real[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : sample_real[0]
						// regulate_c_name       : sample_real
						// input_type_conversion : *(int*)&sample_real[i_0]
						if (&(sample_real[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> sample_real_tmp_mem;
							sample_real_tmp_mem = *(int*)&sample_real[i_0];
							sample_real_tvin_wrapc_buffer[hls_map_index].range(31, 0) = sample_real_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 256; i++)
		{
			sprintf(tvin_sample_real, "%s\n", (sample_real_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_sample_real, tvin_sample_real);
		}

		tcl_file.set_num(256, &tcl_file.sample_real_depth);
		sprintf(tvin_sample_real, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_sample_real, tvin_sample_real);

		// release memory allocation
		delete [] sample_real_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_sample_imag, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_sample_imag, tvin_sample_imag);

		sc_bv<32>* sample_imag_tvin_wrapc_buffer = new sc_bv<32>[256];

		// RTL Name: sample_imag
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: sample_imag(31, 0)
				{
					// carray: (0) => (255) @ (1)
					for (int i_0 = 0; i_0 <= 255; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : sample_imag[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : sample_imag[0]
						// regulate_c_name       : sample_imag
						// input_type_conversion : *(int*)&sample_imag[i_0]
						if (&(sample_imag[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> sample_imag_tmp_mem;
							sample_imag_tmp_mem = *(int*)&sample_imag[i_0];
							sample_imag_tvin_wrapc_buffer[hls_map_index].range(31, 0) = sample_imag_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 256; i++)
		{
			sprintf(tvin_sample_imag, "%s\n", (sample_imag_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_sample_imag, tvin_sample_imag);
		}

		tcl_file.set_num(256, &tcl_file.sample_imag_depth);
		sprintf(tvin_sample_imag, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_sample_imag, tvin_sample_imag);

		// release memory allocation
		delete [] sample_imag_tvin_wrapc_buffer;

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		dft(sample_real, sample_imag);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_sample_real, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_sample_real, tvout_sample_real);

		sc_bv<32>* sample_real_tvout_wrapc_buffer = new sc_bv<32>[256];

		// RTL Name: sample_real
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: sample_real(31, 0)
				{
					// carray: (0) => (255) @ (1)
					for (int i_0 = 0; i_0 <= 255; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : sample_real[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : sample_real[0]
						// regulate_c_name       : sample_real
						// input_type_conversion : *(int*)&sample_real[i_0]
						if (&(sample_real[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> sample_real_tmp_mem;
							sample_real_tmp_mem = *(int*)&sample_real[i_0];
							sample_real_tvout_wrapc_buffer[hls_map_index].range(31, 0) = sample_real_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 256; i++)
		{
			sprintf(tvout_sample_real, "%s\n", (sample_real_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_sample_real, tvout_sample_real);
		}

		tcl_file.set_num(256, &tcl_file.sample_real_depth);
		sprintf(tvout_sample_real, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_sample_real, tvout_sample_real);

		// release memory allocation
		delete [] sample_real_tvout_wrapc_buffer;

		// [[transaction]]
		sprintf(tvout_sample_imag, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_sample_imag, tvout_sample_imag);

		sc_bv<32>* sample_imag_tvout_wrapc_buffer = new sc_bv<32>[256];

		// RTL Name: sample_imag
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: sample_imag(31, 0)
				{
					// carray: (0) => (255) @ (1)
					for (int i_0 = 0; i_0 <= 255; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : sample_imag[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : sample_imag[0]
						// regulate_c_name       : sample_imag
						// input_type_conversion : *(int*)&sample_imag[i_0]
						if (&(sample_imag[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> sample_imag_tmp_mem;
							sample_imag_tmp_mem = *(int*)&sample_imag[i_0];
							sample_imag_tvout_wrapc_buffer[hls_map_index].range(31, 0) = sample_imag_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 256; i++)
		{
			sprintf(tvout_sample_imag, "%s\n", (sample_imag_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_sample_imag, tvout_sample_imag);
		}

		tcl_file.set_num(256, &tcl_file.sample_imag_depth);
		sprintf(tvout_sample_imag, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_sample_imag, tvout_sample_imag);

		// release memory allocation
		delete [] sample_imag_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "sample_real"
		delete [] tvin_sample_real;
		delete [] tvout_sample_real;
		// release memory allocation: "sample_imag"
		delete [] tvin_sample_imag;
		delete [] tvout_sample_imag;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

