// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dft.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dft::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dft::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<44> dft::ap_ST_fsm_state1 = "1";
const sc_lv<44> dft::ap_ST_fsm_state2 = "10";
const sc_lv<44> dft::ap_ST_fsm_state3 = "100";
const sc_lv<44> dft::ap_ST_fsm_state4 = "1000";
const sc_lv<44> dft::ap_ST_fsm_state5 = "10000";
const sc_lv<44> dft::ap_ST_fsm_state6 = "100000";
const sc_lv<44> dft::ap_ST_fsm_state7 = "1000000";
const sc_lv<44> dft::ap_ST_fsm_state8 = "10000000";
const sc_lv<44> dft::ap_ST_fsm_state9 = "100000000";
const sc_lv<44> dft::ap_ST_fsm_state10 = "1000000000";
const sc_lv<44> dft::ap_ST_fsm_state11 = "10000000000";
const sc_lv<44> dft::ap_ST_fsm_state12 = "100000000000";
const sc_lv<44> dft::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<44> dft::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<44> dft::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<44> dft::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<44> dft::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<32> dft::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dft::ap_const_lv32_5 = "101";
const sc_lv<32> dft::ap_const_lv32_12 = "10010";
const sc_lv<32> dft::ap_const_lv32_6 = "110";
const sc_lv<32> dft::ap_const_lv32_17 = "10111";
const sc_lv<32> dft::ap_const_lv32_16 = "10110";
const sc_lv<32> dft::ap_const_lv32_1E = "11110";
const sc_lv<32> dft::ap_const_lv32_23 = "100011";
const sc_lv<32> dft::ap_const_lv32_28 = "101000";
const sc_lv<32> dft::ap_const_lv32_1 = "1";
const sc_lv<1> dft::ap_const_lv1_0 = "0";
const sc_lv<32> dft::ap_const_lv32_C = "1100";
const sc_lv<32> dft::ap_const_lv32_D = "1101";
const sc_lv<32> dft::ap_const_lv32_E = "1110";
const sc_lv<32> dft::ap_const_lv32_19 = "11001";
const bool dft::ap_const_boolean_0 = false;
const sc_lv<32> dft::ap_const_lv32_1A = "11010";
const sc_lv<32> dft::ap_const_lv32_2A = "101010";
const sc_lv<9> dft::ap_const_lv9_0 = "000000000";
const sc_lv<1> dft::ap_const_lv1_1 = "1";
const sc_lv<32> dft::ap_const_lv32_29 = "101001";
const sc_lv<32> dft::ap_const_lv32_2B = "101011";
const sc_lv<32> dft::ap_const_lv32_18 = "11000";
const sc_lv<32> dft::ap_const_lv32_1F = "11111";
const sc_lv<32> dft::ap_const_lv32_24 = "100100";
const sc_lv<32> dft::ap_const_lv32_13 = "10011";
const sc_lv<32> dft::ap_const_lv32_1B = "11011";
const sc_lv<64> dft::ap_const_lv64_3F9921FB5444261E = "11111110011001001000011111101101010100010001000010011000011110";
const sc_lv<32> dft::ap_const_lv32_7 = "111";
const sc_lv<9> dft::ap_const_lv9_100 = "100000000";
const sc_lv<9> dft::ap_const_lv9_1 = "1";
const sc_lv<2> dft::ap_const_lv2_0 = "00";
const sc_lv<2> dft::ap_const_lv2_1 = "1";
const bool dft::ap_const_boolean_1 = true;

dft::dft(sc_module_name name) : sc_module(name), mVcdFile(0) {
    temp_real_U = new dft_temp_real("temp_real_U");
    temp_real_U->clk(ap_clk);
    temp_real_U->reset(ap_rst);
    temp_real_U->address0(temp_real_address0);
    temp_real_U->ce0(temp_real_ce0);
    temp_real_U->we0(temp_real_we0);
    temp_real_U->d0(temp_real_d0);
    temp_real_U->q0(temp_real_q0);
    temp_imag_U = new dft_temp_real("temp_imag_U");
    temp_imag_U->clk(ap_clk);
    temp_imag_U->reset(ap_rst);
    temp_imag_U->address0(temp_imag_address0);
    temp_imag_U->ce0(temp_imag_ce0);
    temp_imag_U->we0(temp_imag_we0);
    temp_imag_U->d0(temp_imag_d0);
    temp_imag_U->q0(temp_imag_q0);
    grp_sin_or_cos_double_s_fu_197 = new sin_or_cos_double_s("grp_sin_or_cos_double_s_fu_197");
    grp_sin_or_cos_double_s_fu_197->ap_clk(ap_clk);
    grp_sin_or_cos_double_s_fu_197->ap_rst(ap_rst);
    grp_sin_or_cos_double_s_fu_197->ap_start(grp_sin_or_cos_double_s_fu_197_ap_start);
    grp_sin_or_cos_double_s_fu_197->ap_done(grp_sin_or_cos_double_s_fu_197_ap_done);
    grp_sin_or_cos_double_s_fu_197->ap_idle(grp_sin_or_cos_double_s_fu_197_ap_idle);
    grp_sin_or_cos_double_s_fu_197->ap_ready(grp_sin_or_cos_double_s_fu_197_ap_ready);
    grp_sin_or_cos_double_s_fu_197->t_in(reg_284);
    grp_sin_or_cos_double_s_fu_197->do_cos(grp_sin_or_cos_double_s_fu_197_do_cos);
    grp_sin_or_cos_double_s_fu_197->ap_return(grp_sin_or_cos_double_s_fu_197_ap_return);
    grp_sin_or_cos_double_s_fu_216 = new sin_or_cos_double_s("grp_sin_or_cos_double_s_fu_216");
    grp_sin_or_cos_double_s_fu_216->ap_clk(ap_clk);
    grp_sin_or_cos_double_s_fu_216->ap_rst(ap_rst);
    grp_sin_or_cos_double_s_fu_216->ap_start(grp_sin_or_cos_double_s_fu_216_ap_start);
    grp_sin_or_cos_double_s_fu_216->ap_done(grp_sin_or_cos_double_s_fu_216_ap_done);
    grp_sin_or_cos_double_s_fu_216->ap_idle(grp_sin_or_cos_double_s_fu_216_ap_idle);
    grp_sin_or_cos_double_s_fu_216->ap_ready(grp_sin_or_cos_double_s_fu_216_ap_ready);
    grp_sin_or_cos_double_s_fu_216->t_in(reg_284);
    grp_sin_or_cos_double_s_fu_216->do_cos(grp_sin_or_cos_double_s_fu_216_do_cos);
    grp_sin_or_cos_double_s_fu_216->ap_return(grp_sin_or_cos_double_s_fu_216_ap_return);
    dft_faddfsub_32nsncg_U34 = new dft_faddfsub_32nsncg<1,5,32,32,32>("dft_faddfsub_32nsncg_U34");
    dft_faddfsub_32nsncg_U34->clk(ap_clk);
    dft_faddfsub_32nsncg_U34->reset(ap_rst);
    dft_faddfsub_32nsncg_U34->din0(grp_fu_235_p0);
    dft_faddfsub_32nsncg_U34->din1(grp_fu_235_p1);
    dft_faddfsub_32nsncg_U34->opcode(grp_fu_235_opcode);
    dft_faddfsub_32nsncg_U34->ce(ap_var_for_const0);
    dft_faddfsub_32nsncg_U34->dout(grp_fu_235_p2);
    dft_faddfsub_32nsncg_U35 = new dft_faddfsub_32nsncg<1,5,32,32,32>("dft_faddfsub_32nsncg_U35");
    dft_faddfsub_32nsncg_U35->clk(ap_clk);
    dft_faddfsub_32nsncg_U35->reset(ap_rst);
    dft_faddfsub_32nsncg_U35->din0(grp_fu_239_p0);
    dft_faddfsub_32nsncg_U35->din1(grp_fu_239_p1);
    dft_faddfsub_32nsncg_U35->opcode(grp_fu_239_opcode);
    dft_faddfsub_32nsncg_U35->ce(ap_var_for_const0);
    dft_faddfsub_32nsncg_U35->dout(grp_fu_239_p2);
    dft_fmul_32ns_32nocq_U36 = new dft_fmul_32ns_32nocq<1,4,32,32,32>("dft_fmul_32ns_32nocq_U36");
    dft_fmul_32ns_32nocq_U36->clk(ap_clk);
    dft_fmul_32ns_32nocq_U36->reset(ap_rst);
    dft_fmul_32ns_32nocq_U36->din0(grp_fu_245_p0);
    dft_fmul_32ns_32nocq_U36->din1(grp_fu_245_p1);
    dft_fmul_32ns_32nocq_U36->ce(ap_var_for_const0);
    dft_fmul_32ns_32nocq_U36->dout(grp_fu_245_p2);
    dft_fmul_32ns_32nocq_U37 = new dft_fmul_32ns_32nocq<1,4,32,32,32>("dft_fmul_32ns_32nocq_U37");
    dft_fmul_32ns_32nocq_U37->clk(ap_clk);
    dft_fmul_32ns_32nocq_U37->reset(ap_rst);
    dft_fmul_32ns_32nocq_U37->din0(sample_imag_load_reg_459);
    dft_fmul_32ns_32nocq_U37->din1(s_reg_447);
    dft_fmul_32ns_32nocq_U37->ce(ap_var_for_const0);
    dft_fmul_32ns_32nocq_U37->dout(grp_fu_249_p2);
    dft_fmul_32ns_32nocq_U38 = new dft_fmul_32ns_32nocq<1,4,32,32,32>("dft_fmul_32ns_32nocq_U38");
    dft_fmul_32ns_32nocq_U38->clk(ap_clk);
    dft_fmul_32ns_32nocq_U38->reset(ap_rst);
    dft_fmul_32ns_32nocq_U38->din0(sample_real_load_reg_453);
    dft_fmul_32ns_32nocq_U38->din1(s_reg_447);
    dft_fmul_32ns_32nocq_U38->ce(ap_var_for_const0);
    dft_fmul_32ns_32nocq_U38->dout(grp_fu_253_p2);
    dft_fmul_32ns_32nocq_U39 = new dft_fmul_32ns_32nocq<1,4,32,32,32>("dft_fmul_32ns_32nocq_U39");
    dft_fmul_32ns_32nocq_U39->clk(ap_clk);
    dft_fmul_32ns_32nocq_U39->reset(ap_rst);
    dft_fmul_32ns_32nocq_U39->din0(sample_imag_load_reg_459);
    dft_fmul_32ns_32nocq_U39->din1(c_reg_441);
    dft_fmul_32ns_32nocq_U39->ce(ap_var_for_const0);
    dft_fmul_32ns_32nocq_U39->dout(grp_fu_257_p2);
    dft_uitofp_32ns_3pcA_U40 = new dft_uitofp_32ns_3pcA<1,5,32,32>("dft_uitofp_32ns_3pcA_U40");
    dft_uitofp_32ns_3pcA_U40->clk(ap_clk);
    dft_uitofp_32ns_3pcA_U40->reset(ap_rst);
    dft_uitofp_32ns_3pcA_U40->din0(grp_fu_261_p0);
    dft_uitofp_32ns_3pcA_U40->ce(ap_var_for_const0);
    dft_uitofp_32ns_3pcA_U40->dout(grp_fu_261_p1);
    dft_fptrunc_64ns_qcK_U41 = new dft_fptrunc_64ns_qcK<1,1,64,32>("dft_fptrunc_64ns_qcK_U41");
    dft_fptrunc_64ns_qcK_U41->din0(grp_fu_264_p0);
    dft_fptrunc_64ns_qcK_U41->dout(grp_fu_264_p1);
    dft_fptrunc_64ns_qcK_U42 = new dft_fptrunc_64ns_qcK<1,1,64,32>("dft_fptrunc_64ns_qcK_U42");
    dft_fptrunc_64ns_qcK_U42->din0(tmp_i_i9_reg_426);
    dft_fptrunc_64ns_qcK_U42->dout(s_fu_267_p1);
    dft_fpext_32ns_64rcU_U43 = new dft_fpext_32ns_64rcU<1,1,32,64>("dft_fpext_32ns_64rcU_U43");
    dft_fpext_32ns_64rcU_U43->din0(grp_fu_270_p0);
    dft_fpext_32ns_64rcU_U43->dout(grp_fu_270_p1);
    dft_dmul_64ns_64nsc4_U44 = new dft_dmul_64ns_64nsc4<1,6,64,64,64>("dft_dmul_64ns_64nsc4_U44");
    dft_dmul_64ns_64nsc4_U44->clk(ap_clk);
    dft_dmul_64ns_64nsc4_U44->reset(ap_rst);
    dft_dmul_64ns_64nsc4_U44->din0(reg_284);
    dft_dmul_64ns_64nsc4_U44->din1(ap_var_for_const1);
    dft_dmul_64ns_64nsc4_U44->ce(ap_var_for_const0);
    dft_dmul_64ns_64nsc4_U44->dout(grp_fu_273_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state31);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state32);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state36);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state37);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state41);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state42);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state43);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state44);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state26_on_subcall_done);
    sensitive << ( grp_sin_or_cos_double_s_fu_197_ap_done );
    sensitive << ( grp_sin_or_cos_double_s_fu_216_ap_done );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( tmp_14_fu_357_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( tmp_14_fu_357_p2 );

    SC_METHOD(thread_grp_fu_235_opcode);
    sensitive << ( ap_CS_fsm_state32 );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_grp_fu_235_p0);
    sensitive << ( reg_291 );
    sensitive << ( tmp_16_reg_162 );
    sensitive << ( ap_CS_fsm_state32 );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_grp_fu_235_p1);
    sensitive << ( reg_297 );
    sensitive << ( tmp_23_reg_465 );
    sensitive << ( ap_CS_fsm_state32 );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_grp_fu_239_opcode);
    sensitive << ( ap_CS_fsm_state32 );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_grp_fu_239_p0);
    sensitive << ( tmp_26_reg_470 );
    sensitive << ( tmp_15_reg_150 );
    sensitive << ( ap_CS_fsm_state32 );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_grp_fu_239_p1);
    sensitive << ( reg_304 );
    sensitive << ( tmp_27_reg_475 );
    sensitive << ( ap_CS_fsm_state32 );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_grp_fu_245_p0);
    sensitive << ( reg_278 );
    sensitive << ( sample_real_load_reg_453 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state28 );

    SC_METHOD(thread_grp_fu_245_p1);
    sensitive << ( w_reg_403 );
    sensitive << ( c_reg_441 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state28 );

    SC_METHOD(thread_grp_fu_261_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_30_fu_323_p1 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( tmp_31_fu_346_p1 );

    SC_METHOD(thread_grp_fu_264_p0);
    sensitive << ( tmp_13_reg_388 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( tmp_i_i_reg_421 );
    sensitive << ( ap_CS_fsm_state27 );

    SC_METHOD(thread_grp_fu_270_p0);
    sensitive << ( reg_278 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( reg_291 );

    SC_METHOD(thread_grp_sin_or_cos_double_s_fu_197_ap_start);
    sensitive << ( grp_sin_or_cos_double_s_fu_197_ap_start_reg );

    SC_METHOD(thread_grp_sin_or_cos_double_s_fu_197_do_cos);
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_grp_sin_or_cos_double_s_fu_216_ap_start);
    sensitive << ( grp_sin_or_cos_double_s_fu_216_ap_start_reg );

    SC_METHOD(thread_grp_sin_or_cos_double_s_fu_216_do_cos);
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_i_4_fu_363_p2);
    sensitive << ( i_1_reg_186 );

    SC_METHOD(thread_i_5_fu_317_p2);
    sensitive << ( i_reg_138 );

    SC_METHOD(thread_j_1_fu_340_p2);
    sensitive << ( j_reg_174 );

    SC_METHOD(thread_sample_imag_address0);
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( tmp_18_reg_488 );
    sensitive << ( ap_CS_fsm_state44 );
    sensitive << ( tmp_21_fu_351_p1 );

    SC_METHOD(thread_sample_imag_ce0);
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( ap_block_state26_on_subcall_done );
    sensitive << ( ap_CS_fsm_state44 );

    SC_METHOD(thread_sample_imag_d0);
    sensitive << ( temp_imag_q0 );
    sensitive << ( ap_CS_fsm_state44 );

    SC_METHOD(thread_sample_imag_we0);
    sensitive << ( ap_CS_fsm_state44 );

    SC_METHOD(thread_sample_real_address0);
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( tmp_18_reg_488 );
    sensitive << ( ap_CS_fsm_state44 );
    sensitive << ( tmp_21_fu_351_p1 );

    SC_METHOD(thread_sample_real_ce0);
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( ap_block_state26_on_subcall_done );
    sensitive << ( ap_CS_fsm_state44 );

    SC_METHOD(thread_sample_real_d0);
    sensitive << ( temp_real_q0 );
    sensitive << ( ap_CS_fsm_state44 );

    SC_METHOD(thread_sample_real_we0);
    sensitive << ( ap_CS_fsm_state44 );

    SC_METHOD(thread_temp_imag_address0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( temp_imag_addr_reg_398 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( tmp_18_fu_369_p1 );
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( tmp_s_fu_328_p1 );

    SC_METHOD(thread_temp_imag_ce0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state42 );

    SC_METHOD(thread_temp_imag_d0);
    sensitive << ( reg_304 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state42 );

    SC_METHOD(thread_temp_imag_we0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state42 );

    SC_METHOD(thread_temp_real_address0);
    sensitive << ( temp_real_addr_reg_393 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( tmp_18_fu_369_p1 );
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( tmp_s_fu_328_p1 );

    SC_METHOD(thread_temp_real_ce0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state42 );

    SC_METHOD(thread_temp_real_d0);
    sensitive << ( reg_297 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state42 );

    SC_METHOD(thread_temp_real_we0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state42 );

    SC_METHOD(thread_tmp_14_fu_357_p2);
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( i_1_reg_186 );

    SC_METHOD(thread_tmp_17_fu_334_p2);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( j_reg_174 );

    SC_METHOD(thread_tmp_18_fu_369_p1);
    sensitive << ( i_1_reg_186 );

    SC_METHOD(thread_tmp_21_fu_351_p1);
    sensitive << ( j_reg_174 );

    SC_METHOD(thread_tmp_30_fu_323_p1);
    sensitive << ( i_reg_138 );

    SC_METHOD(thread_tmp_31_fu_346_p1);
    sensitive << ( j_reg_174 );

    SC_METHOD(thread_tmp_fu_311_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_138 );

    SC_METHOD(thread_tmp_s_fu_328_p1);
    sensitive << ( i_reg_138 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_311_p2 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( tmp_17_fu_334_p2 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( ap_block_state26_on_subcall_done );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( tmp_14_fu_357_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "00000000000000000000000000000000000000000001";
    grp_sin_or_cos_double_s_fu_197_ap_start_reg = SC_LOGIC_0;
    grp_sin_or_cos_double_s_fu_216_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dft_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, sample_real_address0, "(port)sample_real_address0");
    sc_trace(mVcdFile, sample_real_ce0, "(port)sample_real_ce0");
    sc_trace(mVcdFile, sample_real_we0, "(port)sample_real_we0");
    sc_trace(mVcdFile, sample_real_d0, "(port)sample_real_d0");
    sc_trace(mVcdFile, sample_real_q0, "(port)sample_real_q0");
    sc_trace(mVcdFile, sample_imag_address0, "(port)sample_imag_address0");
    sc_trace(mVcdFile, sample_imag_ce0, "(port)sample_imag_ce0");
    sc_trace(mVcdFile, sample_imag_we0, "(port)sample_imag_we0");
    sc_trace(mVcdFile, sample_imag_d0, "(port)sample_imag_d0");
    sc_trace(mVcdFile, sample_imag_q0, "(port)sample_imag_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_261_p1, "grp_fu_261_p1");
    sc_trace(mVcdFile, reg_278, "reg_278");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, grp_fu_270_p1, "grp_fu_270_p1");
    sc_trace(mVcdFile, reg_284, "reg_284");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, grp_fu_245_p2, "grp_fu_245_p2");
    sc_trace(mVcdFile, reg_291, "reg_291");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, ap_CS_fsm_state31, "ap_CS_fsm_state31");
    sc_trace(mVcdFile, grp_fu_235_p2, "grp_fu_235_p2");
    sc_trace(mVcdFile, reg_297, "reg_297");
    sc_trace(mVcdFile, ap_CS_fsm_state36, "ap_CS_fsm_state36");
    sc_trace(mVcdFile, ap_CS_fsm_state41, "ap_CS_fsm_state41");
    sc_trace(mVcdFile, grp_fu_239_p2, "grp_fu_239_p2");
    sc_trace(mVcdFile, reg_304, "reg_304");
    sc_trace(mVcdFile, i_5_fu_317_p2, "i_5_fu_317_p2");
    sc_trace(mVcdFile, i_5_reg_378, "i_5_reg_378");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_30_fu_323_p1, "tmp_30_fu_323_p1");
    sc_trace(mVcdFile, tmp_fu_311_p2, "tmp_fu_311_p2");
    sc_trace(mVcdFile, grp_fu_273_p2, "grp_fu_273_p2");
    sc_trace(mVcdFile, tmp_13_reg_388, "tmp_13_reg_388");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, temp_real_addr_reg_393, "temp_real_addr_reg_393");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, temp_imag_addr_reg_398, "temp_imag_addr_reg_398");
    sc_trace(mVcdFile, grp_fu_264_p1, "grp_fu_264_p1");
    sc_trace(mVcdFile, w_reg_403, "w_reg_403");
    sc_trace(mVcdFile, j_1_fu_340_p2, "j_1_fu_340_p2");
    sc_trace(mVcdFile, j_1_reg_411, "j_1_reg_411");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, tmp_31_fu_346_p1, "tmp_31_fu_346_p1");
    sc_trace(mVcdFile, tmp_17_fu_334_p2, "tmp_17_fu_334_p2");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_197_ap_return, "grp_sin_or_cos_double_s_fu_197_ap_return");
    sc_trace(mVcdFile, tmp_i_i_reg_421, "tmp_i_i_reg_421");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_197_ap_idle, "grp_sin_or_cos_double_s_fu_197_ap_idle");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_197_ap_ready, "grp_sin_or_cos_double_s_fu_197_ap_ready");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_197_ap_done, "grp_sin_or_cos_double_s_fu_197_ap_done");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_216_ap_idle, "grp_sin_or_cos_double_s_fu_216_ap_idle");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_216_ap_ready, "grp_sin_or_cos_double_s_fu_216_ap_ready");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_216_ap_done, "grp_sin_or_cos_double_s_fu_216_ap_done");
    sc_trace(mVcdFile, ap_block_state26_on_subcall_done, "ap_block_state26_on_subcall_done");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_216_ap_return, "grp_sin_or_cos_double_s_fu_216_ap_return");
    sc_trace(mVcdFile, tmp_i_i9_reg_426, "tmp_i_i9_reg_426");
    sc_trace(mVcdFile, c_reg_441, "c_reg_441");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, s_fu_267_p1, "s_fu_267_p1");
    sc_trace(mVcdFile, s_reg_447, "s_reg_447");
    sc_trace(mVcdFile, sample_real_load_reg_453, "sample_real_load_reg_453");
    sc_trace(mVcdFile, sample_imag_load_reg_459, "sample_imag_load_reg_459");
    sc_trace(mVcdFile, grp_fu_249_p2, "grp_fu_249_p2");
    sc_trace(mVcdFile, tmp_23_reg_465, "tmp_23_reg_465");
    sc_trace(mVcdFile, grp_fu_253_p2, "grp_fu_253_p2");
    sc_trace(mVcdFile, tmp_26_reg_470, "tmp_26_reg_470");
    sc_trace(mVcdFile, grp_fu_257_p2, "grp_fu_257_p2");
    sc_trace(mVcdFile, tmp_27_reg_475, "tmp_27_reg_475");
    sc_trace(mVcdFile, i_4_fu_363_p2, "i_4_fu_363_p2");
    sc_trace(mVcdFile, i_4_reg_483, "i_4_reg_483");
    sc_trace(mVcdFile, ap_CS_fsm_state43, "ap_CS_fsm_state43");
    sc_trace(mVcdFile, tmp_18_fu_369_p1, "tmp_18_fu_369_p1");
    sc_trace(mVcdFile, tmp_18_reg_488, "tmp_18_reg_488");
    sc_trace(mVcdFile, tmp_14_fu_357_p2, "tmp_14_fu_357_p2");
    sc_trace(mVcdFile, temp_real_address0, "temp_real_address0");
    sc_trace(mVcdFile, temp_real_ce0, "temp_real_ce0");
    sc_trace(mVcdFile, temp_real_we0, "temp_real_we0");
    sc_trace(mVcdFile, temp_real_d0, "temp_real_d0");
    sc_trace(mVcdFile, temp_real_q0, "temp_real_q0");
    sc_trace(mVcdFile, temp_imag_address0, "temp_imag_address0");
    sc_trace(mVcdFile, temp_imag_ce0, "temp_imag_ce0");
    sc_trace(mVcdFile, temp_imag_we0, "temp_imag_we0");
    sc_trace(mVcdFile, temp_imag_d0, "temp_imag_d0");
    sc_trace(mVcdFile, temp_imag_q0, "temp_imag_q0");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_197_ap_start, "grp_sin_or_cos_double_s_fu_197_ap_start");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_197_do_cos, "grp_sin_or_cos_double_s_fu_197_do_cos");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_216_ap_start, "grp_sin_or_cos_double_s_fu_216_ap_start");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_216_do_cos, "grp_sin_or_cos_double_s_fu_216_do_cos");
    sc_trace(mVcdFile, i_reg_138, "i_reg_138");
    sc_trace(mVcdFile, tmp_15_reg_150, "tmp_15_reg_150");
    sc_trace(mVcdFile, ap_CS_fsm_state42, "ap_CS_fsm_state42");
    sc_trace(mVcdFile, tmp_16_reg_162, "tmp_16_reg_162");
    sc_trace(mVcdFile, j_reg_174, "j_reg_174");
    sc_trace(mVcdFile, i_1_reg_186, "i_1_reg_186");
    sc_trace(mVcdFile, ap_CS_fsm_state44, "ap_CS_fsm_state44");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_197_ap_start_reg, "grp_sin_or_cos_double_s_fu_197_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_216_ap_start_reg, "grp_sin_or_cos_double_s_fu_216_ap_start_reg");
    sc_trace(mVcdFile, tmp_s_fu_328_p1, "tmp_s_fu_328_p1");
    sc_trace(mVcdFile, tmp_21_fu_351_p1, "tmp_21_fu_351_p1");
    sc_trace(mVcdFile, grp_fu_235_p0, "grp_fu_235_p0");
    sc_trace(mVcdFile, grp_fu_235_p1, "grp_fu_235_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state32, "ap_CS_fsm_state32");
    sc_trace(mVcdFile, ap_CS_fsm_state37, "ap_CS_fsm_state37");
    sc_trace(mVcdFile, grp_fu_239_p0, "grp_fu_239_p0");
    sc_trace(mVcdFile, grp_fu_239_p1, "grp_fu_239_p1");
    sc_trace(mVcdFile, grp_fu_245_p0, "grp_fu_245_p0");
    sc_trace(mVcdFile, grp_fu_245_p1, "grp_fu_245_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, grp_fu_261_p0, "grp_fu_261_p0");
    sc_trace(mVcdFile, grp_fu_264_p0, "grp_fu_264_p0");
    sc_trace(mVcdFile, grp_fu_270_p0, "grp_fu_270_p0");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, grp_fu_235_opcode, "grp_fu_235_opcode");
    sc_trace(mVcdFile, grp_fu_239_opcode, "grp_fu_239_opcode");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("dft.hdltvin.dat");
    mHdltvoutHandle.open("dft.hdltvout.dat");
}

dft::~dft() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete temp_real_U;
    delete temp_imag_U;
    delete grp_sin_or_cos_double_s_fu_197;
    delete grp_sin_or_cos_double_s_fu_216;
    delete dft_faddfsub_32nsncg_U34;
    delete dft_faddfsub_32nsncg_U35;
    delete dft_fmul_32ns_32nocq_U36;
    delete dft_fmul_32ns_32nocq_U37;
    delete dft_fmul_32ns_32nocq_U38;
    delete dft_fmul_32ns_32nocq_U39;
    delete dft_uitofp_32ns_3pcA_U40;
    delete dft_fptrunc_64ns_qcK_U41;
    delete dft_fptrunc_64ns_qcK_U42;
    delete dft_fpext_32ns_64rcU_U43;
    delete dft_dmul_64ns_64nsc4_U44;
}

void dft::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void dft::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv64_3F9921FB5444261E;
}

void dft::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_sin_or_cos_double_s_fu_197_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
            grp_sin_or_cos_double_s_fu_197_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sin_or_cos_double_s_fu_197_ap_ready.read())) {
            grp_sin_or_cos_double_s_fu_197_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_sin_or_cos_double_s_fu_216_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
            grp_sin_or_cos_double_s_fu_216_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sin_or_cos_double_s_fu_216_ap_ready.read())) {
            grp_sin_or_cos_double_s_fu_216_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_fu_311_p2.read(), ap_const_lv1_1))) {
        i_1_reg_186 = ap_const_lv9_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read())) {
        i_1_reg_186 = i_4_reg_483.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
         esl_seteq<1,1,1>(tmp_17_fu_334_p2.read(), ap_const_lv1_1))) {
        i_reg_138 = i_5_reg_378.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        i_reg_138 = ap_const_lv9_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        j_reg_174 = j_1_reg_411.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        j_reg_174 = ap_const_lv9_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        tmp_15_reg_150 = reg_304.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        tmp_15_reg_150 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        tmp_16_reg_162 = reg_297.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        tmp_16_reg_162 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        c_reg_441 = grp_fu_264_p1.read();
        s_reg_447 = s_fu_267_p1.read();
        sample_imag_load_reg_459 = sample_imag_q0.read();
        sample_real_load_reg_453 = sample_real_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        i_4_reg_483 = i_4_fu_363_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_5_reg_378 = i_5_fu_317_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        j_1_reg_411 = j_1_fu_340_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
        reg_278 = grp_fu_261_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()))) {
        reg_284 = grp_fu_270_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()))) {
        reg_291 = grp_fu_245_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state36.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()))) {
        reg_297 = grp_fu_235_p2.read();
        reg_304 = grp_fu_239_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        temp_imag_addr_reg_398 =  (sc_lv<8>) (tmp_s_fu_328_p1.read());
        temp_real_addr_reg_393 =  (sc_lv<8>) (tmp_s_fu_328_p1.read());
        w_reg_403 = grp_fu_264_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        tmp_13_reg_388 = grp_fu_273_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()) && esl_seteq<1,1,1>(tmp_14_fu_357_p2.read(), ap_const_lv1_0))) {
        tmp_18_reg_488 = tmp_18_fu_369_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
        tmp_23_reg_465 = grp_fu_249_p2.read();
        tmp_26_reg_470 = grp_fu_253_p2.read();
        tmp_27_reg_475 = grp_fu_257_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state26_on_subcall_done.read()))) {
        tmp_i_i9_reg_426 = grp_sin_or_cos_double_s_fu_216_ap_return.read();
        tmp_i_i_reg_421 = grp_sin_or_cos_double_s_fu_197_ap_return.read();
    }
}

void dft::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dft::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void dft::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void dft::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void dft::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void dft::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dft::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void dft::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void dft::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void dft::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void dft::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void dft::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void dft::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read()[27];
}

void dft::thread_ap_CS_fsm_state31() {
    ap_CS_fsm_state31 = ap_CS_fsm.read()[30];
}

void dft::thread_ap_CS_fsm_state32() {
    ap_CS_fsm_state32 = ap_CS_fsm.read()[31];
}

void dft::thread_ap_CS_fsm_state36() {
    ap_CS_fsm_state36 = ap_CS_fsm.read()[35];
}

void dft::thread_ap_CS_fsm_state37() {
    ap_CS_fsm_state37 = ap_CS_fsm.read()[36];
}

void dft::thread_ap_CS_fsm_state41() {
    ap_CS_fsm_state41 = ap_CS_fsm.read()[40];
}

void dft::thread_ap_CS_fsm_state42() {
    ap_CS_fsm_state42 = ap_CS_fsm.read()[41];
}

void dft::thread_ap_CS_fsm_state43() {
    ap_CS_fsm_state43 = ap_CS_fsm.read()[42];
}

void dft::thread_ap_CS_fsm_state44() {
    ap_CS_fsm_state44 = ap_CS_fsm.read()[43];
}

void dft::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void dft::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void dft::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void dft::thread_ap_block_state26_on_subcall_done() {
    ap_block_state26_on_subcall_done = (esl_seteq<1,1,1>(ap_const_logic_0, grp_sin_or_cos_double_s_fu_197_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_sin_or_cos_double_s_fu_216_ap_done.read()));
}

void dft::thread_ap_done() {
    if ((esl_seteq<1,1,1>(tmp_14_fu_357_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dft::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dft::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(tmp_14_fu_357_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dft::thread_grp_fu_235_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read())) {
        grp_fu_235_opcode = ap_const_lv2_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read())) {
        grp_fu_235_opcode = ap_const_lv2_0;
    } else {
        grp_fu_235_opcode =  (sc_lv<2>) ("XX");
    }
}

void dft::thread_grp_fu_235_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read())) {
        grp_fu_235_p0 = tmp_16_reg_162.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read())) {
        grp_fu_235_p0 = reg_291.read();
    } else {
        grp_fu_235_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_grp_fu_235_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read())) {
        grp_fu_235_p1 = reg_297.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read())) {
        grp_fu_235_p1 = tmp_23_reg_465.read();
    } else {
        grp_fu_235_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_grp_fu_239_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read())) {
        grp_fu_239_opcode = ap_const_lv2_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read())) {
        grp_fu_239_opcode = ap_const_lv2_0;
    } else {
        grp_fu_239_opcode =  (sc_lv<2>) ("XX");
    }
}

void dft::thread_grp_fu_239_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read())) {
        grp_fu_239_p0 = tmp_15_reg_150.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read())) {
        grp_fu_239_p0 = tmp_26_reg_470.read();
    } else {
        grp_fu_239_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_grp_fu_239_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read())) {
        grp_fu_239_p1 = reg_304.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read())) {
        grp_fu_239_p1 = tmp_27_reg_475.read();
    } else {
        grp_fu_239_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_grp_fu_245_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        grp_fu_245_p0 = sample_real_load_reg_453.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_245_p0 = reg_278.read();
    } else {
        grp_fu_245_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_grp_fu_245_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        grp_fu_245_p1 = c_reg_441.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_245_p1 = w_reg_403.read();
    } else {
        grp_fu_245_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_grp_fu_261_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        grp_fu_261_p0 = tmp_31_fu_346_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        grp_fu_261_p0 = tmp_30_fu_323_p1.read();
    } else {
        grp_fu_261_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_grp_fu_264_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        grp_fu_264_p0 = tmp_i_i_reg_421.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        grp_fu_264_p0 = tmp_13_reg_388.read();
    } else {
        grp_fu_264_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_grp_fu_270_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        grp_fu_270_p0 = reg_291.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        grp_fu_270_p0 = reg_278.read();
    } else {
        grp_fu_270_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_grp_sin_or_cos_double_s_fu_197_ap_start() {
    grp_sin_or_cos_double_s_fu_197_ap_start = grp_sin_or_cos_double_s_fu_197_ap_start_reg.read();
}

void dft::thread_grp_sin_or_cos_double_s_fu_197_do_cos() {
    grp_sin_or_cos_double_s_fu_197_do_cos =  (sc_logic) (ap_const_lv1_1[0]);
}

void dft::thread_grp_sin_or_cos_double_s_fu_216_ap_start() {
    grp_sin_or_cos_double_s_fu_216_ap_start = grp_sin_or_cos_double_s_fu_216_ap_start_reg.read();
}

void dft::thread_grp_sin_or_cos_double_s_fu_216_do_cos() {
    grp_sin_or_cos_double_s_fu_216_do_cos =  (sc_logic) (ap_const_lv1_0[0]);
}

void dft::thread_i_4_fu_363_p2() {
    i_4_fu_363_p2 = (!i_1_reg_186.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_1_reg_186.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void dft::thread_i_5_fu_317_p2() {
    i_5_fu_317_p2 = (!i_reg_138.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_reg_138.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void dft::thread_j_1_fu_340_p2() {
    j_1_fu_340_p2 = (!j_reg_174.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(j_reg_174.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void dft::thread_sample_imag_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read())) {
        sample_imag_address0 =  (sc_lv<8>) (tmp_18_reg_488.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        sample_imag_address0 =  (sc_lv<8>) (tmp_21_fu_351_p1.read());
    } else {
        sample_imag_address0 = "XXXXXXXX";
    }
}

void dft::thread_sample_imag_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state26_on_subcall_done.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()))) {
        sample_imag_ce0 = ap_const_logic_1;
    } else {
        sample_imag_ce0 = ap_const_logic_0;
    }
}

void dft::thread_sample_imag_d0() {
    sample_imag_d0 = temp_imag_q0.read();
}

void dft::thread_sample_imag_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read())) {
        sample_imag_we0 = ap_const_logic_1;
    } else {
        sample_imag_we0 = ap_const_logic_0;
    }
}

void dft::thread_sample_real_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read())) {
        sample_real_address0 =  (sc_lv<8>) (tmp_18_reg_488.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        sample_real_address0 =  (sc_lv<8>) (tmp_21_fu_351_p1.read());
    } else {
        sample_real_address0 = "XXXXXXXX";
    }
}

void dft::thread_sample_real_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state26_on_subcall_done.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()))) {
        sample_real_ce0 = ap_const_logic_1;
    } else {
        sample_real_ce0 = ap_const_logic_0;
    }
}

void dft::thread_sample_real_d0() {
    sample_real_d0 = temp_real_q0.read();
}

void dft::thread_sample_real_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read())) {
        sample_real_we0 = ap_const_logic_1;
    } else {
        sample_real_we0 = ap_const_logic_0;
    }
}

void dft::thread_temp_imag_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        temp_imag_address0 =  (sc_lv<8>) (tmp_18_fu_369_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        temp_imag_address0 = temp_imag_addr_reg_398.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        temp_imag_address0 =  (sc_lv<8>) (tmp_s_fu_328_p1.read());
    } else {
        temp_imag_address0 = "XXXXXXXX";
    }
}

void dft::thread_temp_imag_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()))) {
        temp_imag_ce0 = ap_const_logic_1;
    } else {
        temp_imag_ce0 = ap_const_logic_0;
    }
}

void dft::thread_temp_imag_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        temp_imag_d0 = reg_304.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        temp_imag_d0 = ap_const_lv32_0;
    } else {
        temp_imag_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_temp_imag_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()))) {
        temp_imag_we0 = ap_const_logic_1;
    } else {
        temp_imag_we0 = ap_const_logic_0;
    }
}

void dft::thread_temp_real_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        temp_real_address0 =  (sc_lv<8>) (tmp_18_fu_369_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        temp_real_address0 = temp_real_addr_reg_393.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        temp_real_address0 =  (sc_lv<8>) (tmp_s_fu_328_p1.read());
    } else {
        temp_real_address0 = "XXXXXXXX";
    }
}

void dft::thread_temp_real_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()))) {
        temp_real_ce0 = ap_const_logic_1;
    } else {
        temp_real_ce0 = ap_const_logic_0;
    }
}

void dft::thread_temp_real_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        temp_real_d0 = reg_297.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        temp_real_d0 = ap_const_lv32_0;
    } else {
        temp_real_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_temp_real_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()))) {
        temp_real_we0 = ap_const_logic_1;
    } else {
        temp_real_we0 = ap_const_logic_0;
    }
}

void dft::thread_tmp_14_fu_357_p2() {
    tmp_14_fu_357_p2 = (!i_1_reg_186.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i_1_reg_186.read() == ap_const_lv9_100);
}

void dft::thread_tmp_17_fu_334_p2() {
    tmp_17_fu_334_p2 = (!j_reg_174.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_174.read() == ap_const_lv9_100);
}

void dft::thread_tmp_18_fu_369_p1() {
    tmp_18_fu_369_p1 = esl_zext<64,9>(i_1_reg_186.read());
}

void dft::thread_tmp_21_fu_351_p1() {
    tmp_21_fu_351_p1 = esl_zext<64,9>(j_reg_174.read());
}

void dft::thread_tmp_30_fu_323_p1() {
    tmp_30_fu_323_p1 = esl_zext<32,9>(i_reg_138.read());
}

void dft::thread_tmp_31_fu_346_p1() {
    tmp_31_fu_346_p1 = esl_zext<32,9>(j_reg_174.read());
}

void dft::thread_tmp_fu_311_p2() {
    tmp_fu_311_p2 = (!i_reg_138.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_138.read() == ap_const_lv9_100);
}

void dft::thread_tmp_s_fu_328_p1() {
    tmp_s_fu_328_p1 = esl_zext<64,9>(i_reg_138.read());
}

void dft::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_fu_311_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state43;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(tmp_17_fu_334_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state26_on_subcall_done.read()))) {
                ap_NS_fsm = ap_ST_fsm_state27;
            } else {
                ap_NS_fsm = ap_ST_fsm_state26;
            }
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state34;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state38;
            break;
        case 137438953472 : 
            ap_NS_fsm = ap_ST_fsm_state39;
            break;
        case 274877906944 : 
            ap_NS_fsm = ap_ST_fsm_state40;
            break;
        case 549755813888 : 
            ap_NS_fsm = ap_ST_fsm_state41;
            break;
        case 1099511627776 : 
            ap_NS_fsm = ap_ST_fsm_state42;
            break;
        case 2199023255552 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 4398046511104 : 
            if ((esl_seteq<1,1,1>(tmp_14_fu_357_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state44;
            }
            break;
        case 8796093022208 : 
            ap_NS_fsm = ap_ST_fsm_state43;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<44>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void dft::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sample_real_address0\" :  \"" << sample_real_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sample_real_ce0\" :  \"" << sample_real_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sample_real_we0\" :  \"" << sample_real_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sample_real_d0\" :  \"" << sample_real_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"sample_real_q0\" :  \"" << sample_real_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sample_imag_address0\" :  \"" << sample_imag_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sample_imag_ce0\" :  \"" << sample_imag_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sample_imag_we0\" :  \"" << sample_imag_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sample_imag_d0\" :  \"" << sample_imag_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"sample_imag_q0\" :  \"" << sample_imag_q0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

