// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "scaled_fixed2ieee.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic scaled_fixed2ieee::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic scaled_fixed2ieee::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> scaled_fixed2ieee::ap_ST_fsm_state1 = "1";
const sc_lv<8> scaled_fixed2ieee::ap_ST_fsm_state2 = "10";
const sc_lv<8> scaled_fixed2ieee::ap_ST_fsm_state3 = "100";
const sc_lv<8> scaled_fixed2ieee::ap_ST_fsm_state4 = "1000";
const sc_lv<8> scaled_fixed2ieee::ap_ST_fsm_state5 = "10000";
const sc_lv<8> scaled_fixed2ieee::ap_ST_fsm_state6 = "100000";
const sc_lv<8> scaled_fixed2ieee::ap_ST_fsm_state7 = "1000000";
const sc_lv<8> scaled_fixed2ieee::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_1 = "1";
const sc_lv<1> scaled_fixed2ieee::ap_const_lv1_0 = "0";
const sc_lv<1> scaled_fixed2ieee::ap_const_lv1_1 = "1";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_2 = "10";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_4 = "100";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_5 = "101";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_6 = "110";
const sc_lv<2> scaled_fixed2ieee::ap_const_lv2_0 = "00";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_3 = "11";
const sc_lv<2> scaled_fixed2ieee::ap_const_lv2_1 = "1";
const sc_lv<3> scaled_fixed2ieee::ap_const_lv3_0 = "000";
const sc_lv<2> scaled_fixed2ieee::ap_const_lv2_3 = "11";
const sc_lv<2> scaled_fixed2ieee::ap_const_lv2_2 = "10";
const sc_lv<4> scaled_fixed2ieee::ap_const_lv4_0 = "0000";
const sc_lv<6> scaled_fixed2ieee::ap_const_lv6_3E = "111110";
const sc_lv<6> scaled_fixed2ieee::ap_const_lv6_2F = "101111";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_10 = "10000";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_1F = "11111";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_3E = "111110";
const sc_lv<63> scaled_fixed2ieee::ap_const_lv63_7FFFFFFFFFFFFFFF = "111111111111111111111111111111111111111111111111111111111111111";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_F = "1111";
const sc_lv<3> scaled_fixed2ieee::ap_const_lv3_4 = "100";
const sc_lv<3> scaled_fixed2ieee::ap_const_lv3_1 = "1";
const sc_lv<63> scaled_fixed2ieee::ap_const_lv63_0 = "000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<12> scaled_fixed2ieee::ap_const_lv12_3FF = "1111111111";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_7 = "111";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_A = "1010";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_3D = "111101";
const sc_lv<52> scaled_fixed2ieee::ap_const_lv52_0 = "0000000000000000000000000000000000000000000000000000";
const sc_lv<11> scaled_fixed2ieee::ap_const_lv11_0 = "00000000000";
const sc_lv<64> scaled_fixed2ieee::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const bool scaled_fixed2ieee::ap_const_boolean_1 = true;

scaled_fixed2ieee::scaled_fixed2ieee(sc_module_name name) : sc_module(name), mVcdFile(0) {
    dft_mux_42_32_1_1_U1 = new dft_mux_42_32_1_1<1,1,32,32,32,32,2,32>("dft_mux_42_32_1_1_U1");
    dft_mux_42_32_1_1_U1->din0(out_bits_2_V_load_reg_676);
    dft_mux_42_32_1_1_U1->din1(out_bits_2_V_1_load_reg_682);
    dft_mux_42_32_1_1_U1->din2(out_bits_2_V_2_load_reg_688);
    dft_mux_42_32_1_1_U1->din3(p_Result_28_reg_746);
    dft_mux_42_32_1_1_U1->din4(p_Val2_30_fu_423_p5);
    dft_mux_42_32_1_1_U1->dout(p_Val2_30_fu_423_p6);
    dft_mux_42_32_1_1_U2 = new dft_mux_42_32_1_1<1,1,32,32,32,32,2,32>("dft_mux_42_32_1_1_U2");
    dft_mux_42_32_1_1_U2->din0(c_3_1_fu_114);
    dft_mux_42_32_1_1_U2->din1(c_3_2_fu_118);
    dft_mux_42_32_1_1_U2->din2(c_3_3_fu_122);
    dft_mux_42_32_1_1_U2->din3(c_3_fu_110);
    dft_mux_42_32_1_1_U2->din4(sh_assign_fu_501_p5);
    dft_mux_42_32_1_1_U2->dout(sh_assign_fu_501_p6);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Hi_assign_fu_254_p2);
    sensitive << ( tmp_7_fu_246_p3 );

    SC_METHOD(thread_Lo_assign_fu_260_p2);
    sensitive << ( tmp_7_fu_246_p3 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( result_write_assign_fu_640_p1 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_c_0_fu_443_p3);
    sensitive << ( p_Result_29_fu_433_p4 );

    SC_METHOD(thread_exitcond1_fu_234_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_138 );

    SC_METHOD(thread_exitcond_fu_407_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i1_reg_161 );

    SC_METHOD(thread_i_1_fu_240_p2);
    sensitive << ( i_reg_138 );

    SC_METHOD(thread_i_2_fu_413_p2);
    sensitive << ( i1_reg_161 );

    SC_METHOD(thread_i_3_fu_479_p2);
    sensitive << ( i2_reg_194 );

    SC_METHOD(thread_in_shift_V_fu_555_p3);
    sensitive << ( isNeg_reg_783 );
    sensitive << ( tmp_5_fu_549_p2 );
    sensitive << ( tmp_8_fu_543_p2 );

    SC_METHOD(thread_newexp_fu_581_p2);
    sensitive << ( shift_1_reg_215 );
    sensitive << ( tmp_cast_fu_577_p1 );

    SC_METHOD(thread_or_cond_fu_595_p2);
    sensitive << ( tmp_10_reg_809 );
    sensitive << ( tmp_40_fu_587_p3 );

    SC_METHOD(thread_out_bits_0_V_fu_380_p5);
    sensitive << ( p_Val2_2_reg_150 );
    sensitive << ( tmp_6_fu_373_p3 );

    SC_METHOD(thread_out_exp_V_fu_622_p3);
    sensitive << ( or_cond_fu_595_p2 );
    sensitive << ( tmp_41_fu_600_p1 );

    SC_METHOD(thread_p_Result_28_fu_283_p5);
    sensitive << ( tmp_fu_275_p3 );

    SC_METHOD(thread_p_Result_29_fu_433_p4);
    sensitive << ( p_Val2_30_fu_423_p6 );

    SC_METHOD(thread_p_Result_30_fu_630_p4);
    sensitive << ( out_exp_V_fu_622_p3 );
    sensitive << ( p_Val2_31_fu_614_p3 );

    SC_METHOD(thread_p_Result_s_fu_363_p2);
    sensitive << ( tmp_32_fu_351_p2 );
    sensitive << ( tmp_33_fu_357_p2 );

    SC_METHOD(thread_p_Val2_30_fu_423_p5);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i1_reg_161 );

    SC_METHOD(thread_p_Val2_31_fu_614_p3);
    sensitive << ( or_cond_fu_595_p2 );
    sensitive << ( phitmp2_fu_604_p4 );

    SC_METHOD(thread_phitmp2_fu_604_p4);
    sensitive << ( p_Val2_s_reg_205 );

    SC_METHOD(thread_result_write_assign_fu_640_p1);
    sensitive << ( p_Result_30_fu_630_p4 );

    SC_METHOD(thread_sh_assign_1_fu_534_p3);
    sensitive << ( sh_assign_reg_776 );
    sensitive << ( isNeg_reg_783 );
    sensitive << ( tmp_3_reg_789 );

    SC_METHOD(thread_sh_assign_fu_501_p5);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i2_reg_194 );

    SC_METHOD(thread_shift_2_fu_529_p2);
    sensitive << ( sh_assign_reg_776 );
    sensitive << ( shift_reg_182 );

    SC_METHOD(thread_tmp_10_fu_567_p2);
    sensitive << ( in_V );
    sensitive << ( tmp_37_reg_767 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_9_fu_562_p2 );

    SC_METHOD(thread_tmp_20_fu_272_p1);
    sensitive << ( in_V );

    SC_METHOD(thread_tmp_21_fu_295_p2);
    sensitive << ( Hi_assign_reg_702 );
    sensitive << ( Lo_assign_reg_709 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_tmp_22_fu_299_p4);
    sensitive << ( in_V );

    SC_METHOD(thread_tmp_23_fu_308_p2);
    sensitive << ( Hi_assign_reg_702 );
    sensitive << ( Lo_assign_reg_709 );

    SC_METHOD(thread_tmp_24_fu_266_p2);
    sensitive << ( Lo_assign_fu_260_p2 );

    SC_METHOD(thread_tmp_25_fu_312_p2);
    sensitive << ( Hi_assign_reg_702 );
    sensitive << ( Lo_assign_reg_709 );

    SC_METHOD(thread_tmp_26_fu_316_p3);
    sensitive << ( tmp_21_fu_295_p2 );
    sensitive << ( tmp_23_fu_308_p2 );
    sensitive << ( tmp_25_fu_312_p2 );

    SC_METHOD(thread_tmp_27_fu_324_p3);
    sensitive << ( in_V );
    sensitive << ( tmp_21_fu_295_p2 );
    sensitive << ( tmp_22_fu_299_p4 );

    SC_METHOD(thread_tmp_28_fu_331_p3);
    sensitive << ( Lo_assign_reg_709 );
    sensitive << ( tmp_24_reg_717 );
    sensitive << ( tmp_21_fu_295_p2 );

    SC_METHOD(thread_tmp_29_fu_337_p2);
    sensitive << ( tmp_26_fu_316_p3 );

    SC_METHOD(thread_tmp_30_fu_343_p1);
    sensitive << ( tmp_28_fu_331_p3 );

    SC_METHOD(thread_tmp_31_fu_347_p1);
    sensitive << ( tmp_29_fu_337_p2 );

    SC_METHOD(thread_tmp_32_fu_351_p2);
    sensitive << ( tmp_27_fu_324_p3 );
    sensitive << ( tmp_30_fu_343_p1 );

    SC_METHOD(thread_tmp_33_fu_357_p2);
    sensitive << ( tmp_31_fu_347_p1 );

    SC_METHOD(thread_tmp_35_fu_419_p1);
    sensitive << ( i1_reg_161 );

    SC_METHOD(thread_tmp_36_fu_369_p1);
    sensitive << ( p_Result_s_fu_363_p2 );

    SC_METHOD(thread_tmp_37_fu_471_p3);
    sensitive << ( i2_reg_194 );

    SC_METHOD(thread_tmp_3_fu_523_p2);
    sensitive << ( sh_assign_fu_501_p6 );

    SC_METHOD(thread_tmp_40_fu_587_p3);
    sensitive << ( newexp_fu_581_p2 );

    SC_METHOD(thread_tmp_41_fu_600_p1);
    sensitive << ( newexp_fu_581_p2 );

    SC_METHOD(thread_tmp_4_fu_539_p1);
    sensitive << ( sh_assign_1_fu_534_p3 );

    SC_METHOD(thread_tmp_5_fu_549_p2);
    sensitive << ( in_shift_reg_172 );
    sensitive << ( tmp_4_fu_539_p1 );

    SC_METHOD(thread_tmp_6_fu_373_p3);
    sensitive << ( tmp_36_reg_751 );

    SC_METHOD(thread_tmp_7_fu_246_p3);
    sensitive << ( i_reg_138 );

    SC_METHOD(thread_tmp_8_fu_543_p2);
    sensitive << ( in_shift_reg_172 );
    sensitive << ( tmp_4_fu_539_p1 );

    SC_METHOD(thread_tmp_9_fu_562_p2);
    sensitive << ( tmp_37_reg_767 );
    sensitive << ( sh_assign_reg_776 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_tmp_cast_fu_577_p1);
    sensitive << ( tmp_s_fu_572_p2 );

    SC_METHOD(thread_tmp_fu_275_p3);
    sensitive << ( tmp_20_fu_272_p1 );

    SC_METHOD(thread_tmp_s_fu_572_p2);
    sensitive << ( prescale );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_234_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_37_reg_767 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_9_fu_562_p2 );
    sensitive << ( exitcond_fu_407_p2 );

    ap_CS_fsm = "00000001";
    ap_return_preg = "0000000000000000000000000000000000000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "scaled_fixed2ieee_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_V, "(port)in_V");
    sc_trace(mVcdFile, prescale, "(port)prescale");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, out_bits_2_V_load_reg_676, "out_bits_2_V_load_reg_676");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, out_bits_2_V_1_load_reg_682, "out_bits_2_V_1_load_reg_682");
    sc_trace(mVcdFile, out_bits_2_V_2_load_reg_688, "out_bits_2_V_2_load_reg_688");
    sc_trace(mVcdFile, i_1_fu_240_p2, "i_1_fu_240_p2");
    sc_trace(mVcdFile, i_1_reg_697, "i_1_reg_697");
    sc_trace(mVcdFile, Hi_assign_fu_254_p2, "Hi_assign_fu_254_p2");
    sc_trace(mVcdFile, Hi_assign_reg_702, "Hi_assign_reg_702");
    sc_trace(mVcdFile, exitcond1_fu_234_p2, "exitcond1_fu_234_p2");
    sc_trace(mVcdFile, Lo_assign_fu_260_p2, "Lo_assign_fu_260_p2");
    sc_trace(mVcdFile, Lo_assign_reg_709, "Lo_assign_reg_709");
    sc_trace(mVcdFile, tmp_24_fu_266_p2, "tmp_24_fu_266_p2");
    sc_trace(mVcdFile, tmp_24_reg_717, "tmp_24_reg_717");
    sc_trace(mVcdFile, p_Result_28_fu_283_p5, "p_Result_28_fu_283_p5");
    sc_trace(mVcdFile, p_Result_28_reg_746, "p_Result_28_reg_746");
    sc_trace(mVcdFile, tmp_36_fu_369_p1, "tmp_36_fu_369_p1");
    sc_trace(mVcdFile, tmp_36_reg_751, "tmp_36_reg_751");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_2_fu_413_p2, "i_2_fu_413_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_37_fu_471_p3, "tmp_37_fu_471_p3");
    sc_trace(mVcdFile, tmp_37_reg_767, "tmp_37_reg_767");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, i_3_fu_479_p2, "i_3_fu_479_p2");
    sc_trace(mVcdFile, i_3_reg_771, "i_3_reg_771");
    sc_trace(mVcdFile, sh_assign_fu_501_p6, "sh_assign_fu_501_p6");
    sc_trace(mVcdFile, sh_assign_reg_776, "sh_assign_reg_776");
    sc_trace(mVcdFile, isNeg_reg_783, "isNeg_reg_783");
    sc_trace(mVcdFile, tmp_3_fu_523_p2, "tmp_3_fu_523_p2");
    sc_trace(mVcdFile, tmp_3_reg_789, "tmp_3_reg_789");
    sc_trace(mVcdFile, shift_2_fu_529_p2, "shift_2_fu_529_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, in_shift_V_fu_555_p3, "in_shift_V_fu_555_p3");
    sc_trace(mVcdFile, tmp_10_fu_567_p2, "tmp_10_fu_567_p2");
    sc_trace(mVcdFile, tmp_10_reg_809, "tmp_10_reg_809");
    sc_trace(mVcdFile, tmp_9_fu_562_p2, "tmp_9_fu_562_p2");
    sc_trace(mVcdFile, i_reg_138, "i_reg_138");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, p_Val2_2_reg_150, "p_Val2_2_reg_150");
    sc_trace(mVcdFile, i1_reg_161, "i1_reg_161");
    sc_trace(mVcdFile, exitcond_fu_407_p2, "exitcond_fu_407_p2");
    sc_trace(mVcdFile, in_shift_reg_172, "in_shift_reg_172");
    sc_trace(mVcdFile, shift_reg_182, "shift_reg_182");
    sc_trace(mVcdFile, i2_reg_194, "i2_reg_194");
    sc_trace(mVcdFile, p_Val2_s_reg_205, "p_Val2_s_reg_205");
    sc_trace(mVcdFile, shift_1_reg_215, "shift_1_reg_215");
    sc_trace(mVcdFile, out_bits_2_V_fu_98, "out_bits_2_V_fu_98");
    sc_trace(mVcdFile, out_bits_0_V_fu_380_p5, "out_bits_0_V_fu_380_p5");
    sc_trace(mVcdFile, out_bits_2_V_1_fu_102, "out_bits_2_V_1_fu_102");
    sc_trace(mVcdFile, out_bits_2_V_2_fu_106, "out_bits_2_V_2_fu_106");
    sc_trace(mVcdFile, c_3_fu_110, "c_3_fu_110");
    sc_trace(mVcdFile, c_0_fu_443_p3, "c_0_fu_443_p3");
    sc_trace(mVcdFile, tmp_35_fu_419_p1, "tmp_35_fu_419_p1");
    sc_trace(mVcdFile, c_3_1_fu_114, "c_3_1_fu_114");
    sc_trace(mVcdFile, c_3_2_fu_118, "c_3_2_fu_118");
    sc_trace(mVcdFile, c_3_3_fu_122, "c_3_3_fu_122");
    sc_trace(mVcdFile, tmp_7_fu_246_p3, "tmp_7_fu_246_p3");
    sc_trace(mVcdFile, tmp_20_fu_272_p1, "tmp_20_fu_272_p1");
    sc_trace(mVcdFile, tmp_fu_275_p3, "tmp_fu_275_p3");
    sc_trace(mVcdFile, tmp_21_fu_295_p2, "tmp_21_fu_295_p2");
    sc_trace(mVcdFile, tmp_23_fu_308_p2, "tmp_23_fu_308_p2");
    sc_trace(mVcdFile, tmp_25_fu_312_p2, "tmp_25_fu_312_p2");
    sc_trace(mVcdFile, tmp_22_fu_299_p4, "tmp_22_fu_299_p4");
    sc_trace(mVcdFile, tmp_26_fu_316_p3, "tmp_26_fu_316_p3");
    sc_trace(mVcdFile, tmp_28_fu_331_p3, "tmp_28_fu_331_p3");
    sc_trace(mVcdFile, tmp_29_fu_337_p2, "tmp_29_fu_337_p2");
    sc_trace(mVcdFile, tmp_27_fu_324_p3, "tmp_27_fu_324_p3");
    sc_trace(mVcdFile, tmp_30_fu_343_p1, "tmp_30_fu_343_p1");
    sc_trace(mVcdFile, tmp_31_fu_347_p1, "tmp_31_fu_347_p1");
    sc_trace(mVcdFile, tmp_32_fu_351_p2, "tmp_32_fu_351_p2");
    sc_trace(mVcdFile, tmp_33_fu_357_p2, "tmp_33_fu_357_p2");
    sc_trace(mVcdFile, p_Result_s_fu_363_p2, "p_Result_s_fu_363_p2");
    sc_trace(mVcdFile, tmp_6_fu_373_p3, "tmp_6_fu_373_p3");
    sc_trace(mVcdFile, p_Val2_30_fu_423_p5, "p_Val2_30_fu_423_p5");
    sc_trace(mVcdFile, p_Val2_30_fu_423_p6, "p_Val2_30_fu_423_p6");
    sc_trace(mVcdFile, p_Result_29_fu_433_p4, "p_Result_29_fu_433_p4");
    sc_trace(mVcdFile, sh_assign_fu_501_p5, "sh_assign_fu_501_p5");
    sc_trace(mVcdFile, sh_assign_1_fu_534_p3, "sh_assign_1_fu_534_p3");
    sc_trace(mVcdFile, tmp_4_fu_539_p1, "tmp_4_fu_539_p1");
    sc_trace(mVcdFile, tmp_5_fu_549_p2, "tmp_5_fu_549_p2");
    sc_trace(mVcdFile, tmp_8_fu_543_p2, "tmp_8_fu_543_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, tmp_s_fu_572_p2, "tmp_s_fu_572_p2");
    sc_trace(mVcdFile, tmp_cast_fu_577_p1, "tmp_cast_fu_577_p1");
    sc_trace(mVcdFile, newexp_fu_581_p2, "newexp_fu_581_p2");
    sc_trace(mVcdFile, tmp_40_fu_587_p3, "tmp_40_fu_587_p3");
    sc_trace(mVcdFile, or_cond_fu_595_p2, "or_cond_fu_595_p2");
    sc_trace(mVcdFile, phitmp2_fu_604_p4, "phitmp2_fu_604_p4");
    sc_trace(mVcdFile, tmp_41_fu_600_p1, "tmp_41_fu_600_p1");
    sc_trace(mVcdFile, out_exp_V_fu_622_p3, "out_exp_V_fu_622_p3");
    sc_trace(mVcdFile, p_Val2_31_fu_614_p3, "p_Val2_31_fu_614_p3");
    sc_trace(mVcdFile, p_Result_30_fu_630_p4, "p_Result_30_fu_630_p4");
    sc_trace(mVcdFile, result_write_assign_fu_640_p1, "result_write_assign_fu_640_p1");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

scaled_fixed2ieee::~scaled_fixed2ieee() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete dft_mux_42_32_1_1_U1;
    delete dft_mux_42_32_1_1_U2;
}

void scaled_fixed2ieee::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv64_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
            ap_return_preg = result_write_assign_fu_640_p1.read();
        }
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_407_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        i1_reg_161 = i_2_fu_413_p2.read();
    } else if ((esl_seteq<1,1,1>(exitcond1_fu_234_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        i1_reg_161 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_407_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        i2_reg_194 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(tmp_9_fu_562_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(tmp_37_reg_767.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        i2_reg_194 = i_3_reg_771.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_reg_138 = i_1_reg_697.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_138 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_407_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        in_shift_reg_172 = in_V.read();
    } else if ((esl_seteq<1,1,1>(tmp_9_fu_562_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(tmp_37_reg_767.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        in_shift_reg_172 = in_shift_V_fu_555_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        if (esl_seteq<1,2,2>(ap_const_lv2_0, i_reg_138.read())) {
            p_Val2_2_reg_150 = out_bits_2_V_load_reg_676.read();
        } else if ((!esl_seteq<1,2,2>(ap_const_lv2_0, i_reg_138.read()) && 
                    !esl_seteq<1,2,2>(i_reg_138.read(), ap_const_lv2_1))) {
            p_Val2_2_reg_150 = out_bits_2_V_2_load_reg_688.read();
        } else if (esl_seteq<1,2,2>(i_reg_138.read(), ap_const_lv2_1)) {
            p_Val2_2_reg_150 = out_bits_2_V_1_load_reg_682.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(tmp_37_reg_767.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(tmp_9_fu_562_p2.read(), ap_const_lv1_0))) {
        p_Val2_s_reg_205 = in_shift_V_fu_555_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_37_fu_471_p3.read()))) {
        p_Val2_s_reg_205 = in_shift_reg_172.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(tmp_37_reg_767.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(tmp_9_fu_562_p2.read(), ap_const_lv1_0))) {
        shift_1_reg_215 = shift_2_fu_529_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_37_fu_471_p3.read()))) {
        shift_1_reg_215 = shift_reg_182.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_407_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        shift_reg_182 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(tmp_9_fu_562_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(tmp_37_reg_767.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        shift_reg_182 = shift_2_fu_529_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_234_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        Hi_assign_reg_702 = Hi_assign_fu_254_p2.read();
        Lo_assign_reg_709 = Lo_assign_fu_260_p2.read();
        tmp_24_reg_717 = tmp_24_fu_266_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(exitcond_fu_407_p2.read(), ap_const_lv1_0) && esl_seteq<1,2,2>(ap_const_lv2_0, tmp_35_fu_419_p1.read()))) {
        c_3_1_fu_114 = c_0_fu_443_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(exitcond_fu_407_p2.read(), ap_const_lv1_0) && esl_seteq<1,2,2>(ap_const_lv2_1, tmp_35_fu_419_p1.read()))) {
        c_3_2_fu_118 = c_0_fu_443_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(exitcond_fu_407_p2.read(), ap_const_lv1_0) && esl_seteq<1,2,2>(tmp_35_fu_419_p1.read(), ap_const_lv2_2))) {
        c_3_3_fu_122 = c_0_fu_443_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(exitcond_fu_407_p2.read(), ap_const_lv1_0) && esl_seteq<1,2,2>(tmp_35_fu_419_p1.read(), ap_const_lv2_3))) {
        c_3_fu_110 = c_0_fu_443_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_1_reg_697 = i_1_fu_240_p2.read();
        out_bits_2_V_1_load_reg_682 = out_bits_2_V_1_fu_102.read();
        out_bits_2_V_2_load_reg_688 = out_bits_2_V_2_fu_106.read();
        out_bits_2_V_load_reg_676 = out_bits_2_V_fu_98.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_3_reg_771 = i_3_fu_479_p2.read();
        tmp_37_reg_767 = i2_reg_194.read().range(2, 2);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_37_fu_471_p3.read()))) {
        isNeg_reg_783 = sh_assign_fu_501_p6.read().range(31, 31);
        sh_assign_reg_776 = sh_assign_fu_501_p6.read();
        tmp_3_reg_789 = tmp_3_fu_523_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,2,2>(i_reg_138.read(), ap_const_lv2_1))) {
        out_bits_2_V_1_fu_102 = out_bits_0_V_fu_380_p5.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && !esl_seteq<1,2,2>(ap_const_lv2_0, i_reg_138.read()) && !esl_seteq<1,2,2>(i_reg_138.read(), ap_const_lv2_1))) {
        out_bits_2_V_2_fu_106 = out_bits_0_V_fu_380_p5.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,2,2>(ap_const_lv2_0, i_reg_138.read()))) {
        out_bits_2_V_fu_98 = out_bits_0_V_fu_380_p5.read();
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_234_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        p_Result_28_reg_746 = p_Result_28_fu_283_p5.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && (esl_seteq<1,1,1>(tmp_37_reg_767.read(), ap_const_lv1_1) || 
  esl_seteq<1,1,1>(tmp_9_fu_562_p2.read(), ap_const_lv1_0)))) {
        tmp_10_reg_809 = tmp_10_fu_567_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        tmp_36_reg_751 = tmp_36_fu_369_p1.read();
    }
}

void scaled_fixed2ieee::thread_Hi_assign_fu_254_p2() {
    Hi_assign_fu_254_p2 = (!ap_const_lv6_3E.is_01() || !tmp_7_fu_246_p3.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_3E) - sc_biguint<6>(tmp_7_fu_246_p3.read()));
}

void scaled_fixed2ieee::thread_Lo_assign_fu_260_p2() {
    Lo_assign_fu_260_p2 = (!ap_const_lv6_2F.is_01() || !tmp_7_fu_246_p3.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_2F) - sc_biguint<6>(tmp_7_fu_246_p3.read()));
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void scaled_fixed2ieee::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void scaled_fixed2ieee::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void scaled_fixed2ieee::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void scaled_fixed2ieee::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ap_return = result_write_assign_fu_640_p1.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void scaled_fixed2ieee::thread_c_0_fu_443_p3() {
    c_0_fu_443_p3 = esl_cttz<32,32>(p_Result_29_fu_433_p4.read());
}

void scaled_fixed2ieee::thread_exitcond1_fu_234_p2() {
    exitcond1_fu_234_p2 = (!i_reg_138.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_138.read() == ap_const_lv2_3);
}

void scaled_fixed2ieee::thread_exitcond_fu_407_p2() {
    exitcond_fu_407_p2 = (!i1_reg_161.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_161.read() == ap_const_lv3_4);
}

void scaled_fixed2ieee::thread_i_1_fu_240_p2() {
    i_1_fu_240_p2 = (!i_reg_138.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i_reg_138.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void scaled_fixed2ieee::thread_i_2_fu_413_p2() {
    i_2_fu_413_p2 = (!i1_reg_161.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i1_reg_161.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void scaled_fixed2ieee::thread_i_3_fu_479_p2() {
    i_3_fu_479_p2 = (!i2_reg_194.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i2_reg_194.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void scaled_fixed2ieee::thread_in_shift_V_fu_555_p3() {
    in_shift_V_fu_555_p3 = (!isNeg_reg_783.read()[0].is_01())? sc_lv<63>(): ((isNeg_reg_783.read()[0].to_bool())? tmp_5_fu_549_p2.read(): tmp_8_fu_543_p2.read());
}

void scaled_fixed2ieee::thread_newexp_fu_581_p2() {
    newexp_fu_581_p2 = (!tmp_cast_fu_577_p1.read().is_01() || !shift_1_reg_215.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_cast_fu_577_p1.read()) - sc_biguint<32>(shift_1_reg_215.read()));
}

void scaled_fixed2ieee::thread_or_cond_fu_595_p2() {
    or_cond_fu_595_p2 = (tmp_40_fu_587_p3.read() | tmp_10_reg_809.read());
}

void scaled_fixed2ieee::thread_out_bits_0_V_fu_380_p5() {
    out_bits_0_V_fu_380_p5 = esl_partset<32,32,17,32,32>(p_Val2_2_reg_150.read(), tmp_6_fu_373_p3.read(), ap_const_lv32_F, ap_const_lv32_1F);
}

void scaled_fixed2ieee::thread_out_exp_V_fu_622_p3() {
    out_exp_V_fu_622_p3 = (!or_cond_fu_595_p2.read()[0].is_01())? sc_lv<11>(): ((or_cond_fu_595_p2.read()[0].to_bool())? ap_const_lv11_0: tmp_41_fu_600_p1.read());
}

void scaled_fixed2ieee::thread_p_Result_28_fu_283_p5() {
    p_Result_28_fu_283_p5 = esl_partset<32,32,16,32,32>(ap_const_lv32_0, tmp_fu_275_p3.read(), ap_const_lv32_10, ap_const_lv32_1F);
}

void scaled_fixed2ieee::thread_p_Result_29_fu_433_p4() {
    p_Result_29_fu_433_p4 = p_Val2_30_fu_423_p6.read().range(0, 31);
}

void scaled_fixed2ieee::thread_p_Result_30_fu_630_p4() {
    p_Result_30_fu_630_p4 = esl_concat<12,52>(esl_concat<1,11>(ap_const_lv1_0, out_exp_V_fu_622_p3.read()), p_Val2_31_fu_614_p3.read());
}

void scaled_fixed2ieee::thread_p_Result_s_fu_363_p2() {
    p_Result_s_fu_363_p2 = (tmp_32_fu_351_p2.read() & tmp_33_fu_357_p2.read());
}

void scaled_fixed2ieee::thread_p_Val2_30_fu_423_p5() {
    p_Val2_30_fu_423_p5 = i1_reg_161.read().range(2-1, 0);
}

void scaled_fixed2ieee::thread_p_Val2_31_fu_614_p3() {
    p_Val2_31_fu_614_p3 = (!or_cond_fu_595_p2.read()[0].is_01())? sc_lv<52>(): ((or_cond_fu_595_p2.read()[0].to_bool())? ap_const_lv52_0: phitmp2_fu_604_p4.read());
}

void scaled_fixed2ieee::thread_phitmp2_fu_604_p4() {
    phitmp2_fu_604_p4 = p_Val2_s_reg_205.read().range(61, 10);
}

void scaled_fixed2ieee::thread_result_write_assign_fu_640_p1() {
    result_write_assign_fu_640_p1 = p_Result_30_fu_630_p4.read();
}

void scaled_fixed2ieee::thread_sh_assign_1_fu_534_p3() {
    sh_assign_1_fu_534_p3 = (!isNeg_reg_783.read()[0].is_01())? sc_lv<32>(): ((isNeg_reg_783.read()[0].to_bool())? tmp_3_reg_789.read(): sh_assign_reg_776.read());
}

void scaled_fixed2ieee::thread_sh_assign_fu_501_p5() {
    sh_assign_fu_501_p5 = i2_reg_194.read().range(2-1, 0);
}

void scaled_fixed2ieee::thread_shift_2_fu_529_p2() {
    shift_2_fu_529_p2 = (!sh_assign_reg_776.read().is_01() || !shift_reg_182.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sh_assign_reg_776.read()) + sc_biguint<32>(shift_reg_182.read()));
}

void scaled_fixed2ieee::thread_tmp_10_fu_567_p2() {
    tmp_10_fu_567_p2 = (!in_V.read().is_01() || !ap_const_lv63_0.is_01())? sc_lv<1>(): sc_lv<1>(in_V.read() == ap_const_lv63_0);
}

void scaled_fixed2ieee::thread_tmp_20_fu_272_p1() {
    tmp_20_fu_272_p1 = in_V.read().range(15-1, 0);
}

void scaled_fixed2ieee::thread_tmp_21_fu_295_p2() {
    tmp_21_fu_295_p2 = (!Lo_assign_reg_709.read().is_01() || !Hi_assign_reg_702.read().is_01())? sc_lv<1>(): (sc_biguint<6>(Lo_assign_reg_709.read()) > sc_biguint<6>(Hi_assign_reg_702.read()));
}

void scaled_fixed2ieee::thread_tmp_22_fu_299_p4() {
    tmp_22_fu_299_p4 = in_V.read().range(0, 62);
}

void scaled_fixed2ieee::thread_tmp_23_fu_308_p2() {
    tmp_23_fu_308_p2 = (!Lo_assign_reg_709.read().is_01() || !Hi_assign_reg_702.read().is_01())? sc_lv<6>(): (sc_biguint<6>(Lo_assign_reg_709.read()) - sc_biguint<6>(Hi_assign_reg_702.read()));
}

void scaled_fixed2ieee::thread_tmp_24_fu_266_p2() {
    tmp_24_fu_266_p2 = (!ap_const_lv6_3E.is_01() || !Lo_assign_fu_260_p2.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_3E) - sc_biguint<6>(Lo_assign_fu_260_p2.read()));
}

void scaled_fixed2ieee::thread_tmp_25_fu_312_p2() {
    tmp_25_fu_312_p2 = (!Hi_assign_reg_702.read().is_01() || !Lo_assign_reg_709.read().is_01())? sc_lv<6>(): (sc_biguint<6>(Hi_assign_reg_702.read()) - sc_biguint<6>(Lo_assign_reg_709.read()));
}

void scaled_fixed2ieee::thread_tmp_26_fu_316_p3() {
    tmp_26_fu_316_p3 = (!tmp_21_fu_295_p2.read()[0].is_01())? sc_lv<6>(): ((tmp_21_fu_295_p2.read()[0].to_bool())? tmp_23_fu_308_p2.read(): tmp_25_fu_312_p2.read());
}

void scaled_fixed2ieee::thread_tmp_27_fu_324_p3() {
    tmp_27_fu_324_p3 = (!tmp_21_fu_295_p2.read()[0].is_01())? sc_lv<63>(): ((tmp_21_fu_295_p2.read()[0].to_bool())? tmp_22_fu_299_p4.read(): in_V.read());
}

void scaled_fixed2ieee::thread_tmp_28_fu_331_p3() {
    tmp_28_fu_331_p3 = (!tmp_21_fu_295_p2.read()[0].is_01())? sc_lv<6>(): ((tmp_21_fu_295_p2.read()[0].to_bool())? tmp_24_reg_717.read(): Lo_assign_reg_709.read());
}

void scaled_fixed2ieee::thread_tmp_29_fu_337_p2() {
    tmp_29_fu_337_p2 = (!ap_const_lv6_3E.is_01() || !tmp_26_fu_316_p3.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_3E) - sc_biguint<6>(tmp_26_fu_316_p3.read()));
}

void scaled_fixed2ieee::thread_tmp_30_fu_343_p1() {
    tmp_30_fu_343_p1 = esl_zext<63,6>(tmp_28_fu_331_p3.read());
}

void scaled_fixed2ieee::thread_tmp_31_fu_347_p1() {
    tmp_31_fu_347_p1 = esl_zext<63,6>(tmp_29_fu_337_p2.read());
}

void scaled_fixed2ieee::thread_tmp_32_fu_351_p2() {
    tmp_32_fu_351_p2 = (!tmp_30_fu_343_p1.read().is_01())? sc_lv<63>(): tmp_27_fu_324_p3.read() >> (unsigned short)tmp_30_fu_343_p1.read().to_uint();
}

void scaled_fixed2ieee::thread_tmp_33_fu_357_p2() {
    tmp_33_fu_357_p2 = (!tmp_31_fu_347_p1.read().is_01())? sc_lv<63>(): ap_const_lv63_7FFFFFFFFFFFFFFF >> (unsigned short)tmp_31_fu_347_p1.read().to_uint();
}

void scaled_fixed2ieee::thread_tmp_35_fu_419_p1() {
    tmp_35_fu_419_p1 = i1_reg_161.read().range(2-1, 0);
}

void scaled_fixed2ieee::thread_tmp_36_fu_369_p1() {
    tmp_36_fu_369_p1 = p_Result_s_fu_363_p2.read().range(16-1, 0);
}

void scaled_fixed2ieee::thread_tmp_37_fu_471_p3() {
    tmp_37_fu_471_p3 = i2_reg_194.read().range(2, 2);
}

void scaled_fixed2ieee::thread_tmp_3_fu_523_p2() {
    tmp_3_fu_523_p2 = (!ap_const_lv32_0.is_01() || !sh_assign_fu_501_p6.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(sh_assign_fu_501_p6.read()));
}

void scaled_fixed2ieee::thread_tmp_40_fu_587_p3() {
    tmp_40_fu_587_p3 = newexp_fu_581_p2.read().range(31, 31);
}

void scaled_fixed2ieee::thread_tmp_41_fu_600_p1() {
    tmp_41_fu_600_p1 = newexp_fu_581_p2.read().range(11-1, 0);
}

void scaled_fixed2ieee::thread_tmp_4_fu_539_p1() {
    tmp_4_fu_539_p1 = esl_zext<63,32>(sh_assign_1_fu_534_p3.read());
}

void scaled_fixed2ieee::thread_tmp_5_fu_549_p2() {
    tmp_5_fu_549_p2 = (!in_shift_reg_172.read().is_01() || !tmp_4_fu_539_p1.read().is_01())? sc_lv<63>(): sc_bigint<63>(in_shift_reg_172.read()) >> (unsigned short)tmp_4_fu_539_p1.read().to_uint();
}

void scaled_fixed2ieee::thread_tmp_6_fu_373_p3() {
    tmp_6_fu_373_p3 = esl_concat<16,1>(tmp_36_reg_751.read(), ap_const_lv1_1);
}

void scaled_fixed2ieee::thread_tmp_7_fu_246_p3() {
    tmp_7_fu_246_p3 = esl_concat<2,4>(i_reg_138.read(), ap_const_lv4_0);
}

void scaled_fixed2ieee::thread_tmp_8_fu_543_p2() {
    tmp_8_fu_543_p2 = (!tmp_4_fu_539_p1.read().is_01())? sc_lv<63>(): in_shift_reg_172.read() << (unsigned short)tmp_4_fu_539_p1.read().to_uint();
}

void scaled_fixed2ieee::thread_tmp_9_fu_562_p2() {
    tmp_9_fu_562_p2 = (!sh_assign_reg_776.read().is_01() || !ap_const_lv32_10.is_01())? sc_lv<1>(): sc_lv<1>(sh_assign_reg_776.read() == ap_const_lv32_10);
}

void scaled_fixed2ieee::thread_tmp_cast_fu_577_p1() {
    tmp_cast_fu_577_p1 = esl_sext<32,12>(tmp_s_fu_572_p2.read());
}

void scaled_fixed2ieee::thread_tmp_fu_275_p3() {
    tmp_fu_275_p3 = esl_concat<15,1>(tmp_20_fu_272_p1.read(), ap_const_lv1_1);
}

void scaled_fixed2ieee::thread_tmp_s_fu_572_p2() {
    tmp_s_fu_572_p2 = (!ap_const_lv12_3FF.is_01() || !prescale.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_3FF) - sc_biguint<12>(prescale.read()));
}

void scaled_fixed2ieee::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond1_fu_234_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(exitcond_fu_407_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && (esl_seteq<1,1,1>(tmp_37_reg_767.read(), ap_const_lv1_1) || 
  esl_seteq<1,1,1>(tmp_9_fu_562_p2.read(), ap_const_lv1_0)))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}

}

