// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "sin_or_cos_double_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sin_or_cos_double_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic sin_or_cos_double_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state1 = "1";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state2 = "10";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state3 = "100";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state4 = "1000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state5 = "10000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state6 = "100000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state7 = "1000000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state8 = "10000000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state9 = "100000000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state10 = "1000000000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state11 = "10000000000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state12 = "100000000000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<24> sin_or_cos_double_s::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_1 = "1";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_2 = "10";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_6 = "110";
const sc_lv<1> sin_or_cos_double_s::ap_const_lv1_0 = "0";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_7 = "111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_8 = "1000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_9 = "1001";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_A = "1010";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_B = "1011";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_C = "1100";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_D = "1101";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_E = "1110";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_F = "1111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_10 = "10000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_11 = "10001";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_15 = "10101";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_16 = "10110";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_3F = "111111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_34 = "110100";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_3E = "111110";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_3FE = "1111111110";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_44D = "10001001101";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_4A = "1001010";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_56 = "1010110";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_FF = "11111111";
const sc_lv<1> sin_or_cos_double_s::ap_const_lv1_1 = "1";
const sc_lv<52> sin_or_cos_double_s::ap_const_lv52_0 = "0000000000000000000000000000000000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_2B = "101011";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_A6 = "10100110";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_A7 = "10100111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_A9 = "10101001";
const sc_lv<3> sin_or_cos_double_s::ap_const_lv3_0 = "000";
const sc_lv<124> sin_or_cos_double_s::ap_const_lv124_0 = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_7B = "1111011";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_403 = "10000000011";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_0 = "00000000000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_3D = "111101";
const sc_lv<2> sin_or_cos_double_s::ap_const_lv2_3 = "11";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_7FF = "11111111111";
const sc_lv<12> sin_or_cos_double_s::ap_const_lv12_0 = "000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_38 = "111000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_37 = "110111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_31 = "110001";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_61 = "1100001";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_6B = "1101011";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_2D = "101101";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_5C = "1011100";
const sc_lv<4> sin_or_cos_double_s::ap_const_lv4_0 = "0000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_1F = "11111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_3B = "111011";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_26 = "100110";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_4A = "1001010";
const sc_lv<63> sin_or_cos_double_s::ap_const_lv63_7FFFFFFFFFFFFFFF = "111111111111111111111111111111111111111111111111111111111111111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_7D = "1111101";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_17 = "10111";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_3FF = "1111111111";
const sc_lv<52> sin_or_cos_double_s::ap_const_lv52_FFFFFFFFFFFFF = "1111111111111111111111111111111111111111111111111111";
const bool sin_or_cos_double_s::ap_const_boolean_1 = true;

sin_or_cos_double_s::sin_or_cos_double_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    ref_4oPi_table_256_V_U = new sin_or_cos_doublebkb("ref_4oPi_table_256_V_U");
    ref_4oPi_table_256_V_U->clk(ap_clk);
    ref_4oPi_table_256_V_U->reset(ap_rst);
    ref_4oPi_table_256_V_U->address0(ref_4oPi_table_256_V_address0);
    ref_4oPi_table_256_V_U->ce0(ref_4oPi_table_256_V_ce0);
    ref_4oPi_table_256_V_U->q0(ref_4oPi_table_256_V_q0);
    fourth_order_double_4_U = new sin_or_cos_doublecud("fourth_order_double_4_U");
    fourth_order_double_4_U->clk(ap_clk);
    fourth_order_double_4_U->reset(ap_rst);
    fourth_order_double_4_U->address0(fourth_order_double_4_address0);
    fourth_order_double_4_U->ce0(fourth_order_double_4_ce0);
    fourth_order_double_4_U->q0(fourth_order_double_4_q0);
    fourth_order_double_5_U = new sin_or_cos_doubledEe("fourth_order_double_5_U");
    fourth_order_double_5_U->clk(ap_clk);
    fourth_order_double_5_U->reset(ap_rst);
    fourth_order_double_5_U->address0(fourth_order_double_5_address0);
    fourth_order_double_5_U->ce0(fourth_order_double_5_ce0);
    fourth_order_double_5_U->q0(fourth_order_double_5_q0);
    fourth_order_double_6_U = new sin_or_cos_doubleeOg("fourth_order_double_6_U");
    fourth_order_double_6_U->clk(ap_clk);
    fourth_order_double_6_U->reset(ap_rst);
    fourth_order_double_6_U->address0(fourth_order_double_6_address0);
    fourth_order_double_6_U->ce0(fourth_order_double_6_ce0);
    fourth_order_double_6_U->q0(fourth_order_double_6_q0);
    fourth_order_double_7_U = new sin_or_cos_doublefYi("fourth_order_double_7_U");
    fourth_order_double_7_U->clk(ap_clk);
    fourth_order_double_7_U->reset(ap_rst);
    fourth_order_double_7_U->address0(fourth_order_double_7_address0);
    fourth_order_double_7_U->ce0(fourth_order_double_7_ce0);
    fourth_order_double_7_U->q0(fourth_order_double_7_q0);
    fourth_order_double_s_U = new sin_or_cos_doubleg8j("fourth_order_double_s_U");
    fourth_order_double_s_U->clk(ap_clk);
    fourth_order_double_s_U->reset(ap_rst);
    fourth_order_double_s_U->address0(fourth_order_double_s_address0);
    fourth_order_double_s_U->ce0(fourth_order_double_s_ce0);
    fourth_order_double_s_U->q0(fourth_order_double_s_q0);
    grp_scaled_fixed2ieee_fu_268 = new scaled_fixed2ieee("grp_scaled_fixed2ieee_fu_268");
    grp_scaled_fixed2ieee_fu_268->ap_clk(ap_clk);
    grp_scaled_fixed2ieee_fu_268->ap_rst(ap_rst);
    grp_scaled_fixed2ieee_fu_268->ap_start(grp_scaled_fixed2ieee_fu_268_ap_start);
    grp_scaled_fixed2ieee_fu_268->ap_done(grp_scaled_fixed2ieee_fu_268_ap_done);
    grp_scaled_fixed2ieee_fu_268->ap_idle(grp_scaled_fixed2ieee_fu_268_ap_idle);
    grp_scaled_fixed2ieee_fu_268->ap_ready(grp_scaled_fixed2ieee_fu_268_ap_ready);
    grp_scaled_fixed2ieee_fu_268->in_V(result_V_reg_1414);
    grp_scaled_fixed2ieee_fu_268->prescale(r_V_reg_1419);
    grp_scaled_fixed2ieee_fu_268->ap_return(grp_scaled_fixed2ieee_fu_268_ap_return);
    dft_mul_170ns_53nhbi_U6 = new dft_mul_170ns_53nhbi<1,5,170,53,223>("dft_mul_170ns_53nhbi_U6");
    dft_mul_170ns_53nhbi_U6->clk(ap_clk);
    dft_mul_170ns_53nhbi_U6->reset(ap_rst);
    dft_mul_170ns_53nhbi_U6->din0(grp_fu_372_p0);
    dft_mul_170ns_53nhbi_U6->din1(grp_fu_372_p1);
    dft_mul_170ns_53nhbi_U6->ce(ap_var_for_const0);
    dft_mul_170ns_53nhbi_U6->dout(grp_fu_372_p2);
    dft_mux_83_1_1_1_U7 = new dft_mux_83_1_1_1<1,1,1,1,1,1,1,1,1,1,3,1>("dft_mux_83_1_1_1_U7");
    dft_mux_83_1_1_1_U7->din0(ap_var_for_const1);
    dft_mux_83_1_1_1_U7->din1(ap_var_for_const2);
    dft_mux_83_1_1_1_U7->din2(ap_var_for_const2);
    dft_mux_83_1_1_1_U7->din3(ap_var_for_const1);
    dft_mux_83_1_1_1_U7->din4(ap_var_for_const1);
    dft_mux_83_1_1_1_U7->din5(ap_var_for_const2);
    dft_mux_83_1_1_1_U7->din6(ap_var_for_const2);
    dft_mux_83_1_1_1_U7->din7(ap_var_for_const1);
    dft_mux_83_1_1_1_U7->din8(p_Val2_29_reg_1169);
    dft_mux_83_1_1_1_U7->dout(tmp_fu_596_p10);
    dft_mul_49ns_49nsibs_U8 = new dft_mul_49ns_49nsibs<1,2,49,49,98>("dft_mul_49ns_49nsibs_U8");
    dft_mul_49ns_49nsibs_U8->clk(ap_clk);
    dft_mul_49ns_49nsibs_U8->reset(ap_rst);
    dft_mul_49ns_49nsibs_U8->din0(grp_fu_620_p0);
    dft_mul_49ns_49nsibs_U8->din1(grp_fu_620_p1);
    dft_mul_49ns_49nsibs_U8->ce(ap_var_for_const0);
    dft_mul_49ns_49nsibs_U8->dout(grp_fu_620_p2);
    dft_mul_49ns_49nsibs_U9 = new dft_mul_49ns_49nsibs<1,2,49,49,98>("dft_mul_49ns_49nsibs_U9");
    dft_mul_49ns_49nsibs_U9->clk(ap_clk);
    dft_mul_49ns_49nsibs_U9->reset(ap_rst);
    dft_mul_49ns_49nsibs_U9->din0(grp_fu_664_p0);
    dft_mul_49ns_49nsibs_U9->din1(grp_fu_664_p1);
    dft_mul_49ns_49nsibs_U9->ce(ap_var_for_const0);
    dft_mul_49ns_49nsibs_U9->dout(grp_fu_664_p2);
    dft_mul_49ns_49nsibs_U10 = new dft_mul_49ns_49nsibs<1,2,49,49,98>("dft_mul_49ns_49nsibs_U10");
    dft_mul_49ns_49nsibs_U10->clk(ap_clk);
    dft_mul_49ns_49nsibs_U10->reset(ap_rst);
    dft_mul_49ns_49nsibs_U10->din0(grp_fu_669_p0);
    dft_mul_49ns_49nsibs_U10->din1(grp_fu_669_p1);
    dft_mul_49ns_49nsibs_U10->ce(ap_var_for_const0);
    dft_mul_49ns_49nsibs_U10->dout(grp_fu_669_p2);
    dft_mul_56ns_52s_jbC_U11 = new dft_mul_56ns_52s_jbC<1,2,56,52,108>("dft_mul_56ns_52s_jbC_U11");
    dft_mul_56ns_52s_jbC_U11->clk(ap_clk);
    dft_mul_56ns_52s_jbC_U11->reset(ap_rst);
    dft_mul_56ns_52s_jbC_U11->din0(grp_fu_681_p0);
    dft_mul_56ns_52s_jbC_U11->din1(fourth_order_double_10_reg_1280);
    dft_mul_56ns_52s_jbC_U11->ce(ap_var_for_const0);
    dft_mul_56ns_52s_jbC_U11->dout(grp_fu_681_p2);
    dft_mul_49ns_44s_kbM_U12 = new dft_mul_49ns_44s_kbM<1,2,49,44,93>("dft_mul_49ns_44s_kbM_U12");
    dft_mul_49ns_44s_kbM_U12->clk(ap_clk);
    dft_mul_49ns_44s_kbM_U12->reset(ap_rst);
    dft_mul_49ns_44s_kbM_U12->din0(grp_fu_693_p0);
    dft_mul_49ns_44s_kbM_U12->din1(fourth_order_double_12_reg_1285);
    dft_mul_49ns_44s_kbM_U12->ce(ap_var_for_const0);
    dft_mul_49ns_44s_kbM_U12->dout(grp_fu_693_p2);
    dft_mul_42ns_33nslbW_U13 = new dft_mul_42ns_33nslbW<1,2,42,33,75>("dft_mul_42ns_33nslbW_U13");
    dft_mul_42ns_33nslbW_U13->clk(ap_clk);
    dft_mul_42ns_33nslbW_U13->reset(ap_rst);
    dft_mul_42ns_33nslbW_U13->din0(grp_fu_752_p0);
    dft_mul_42ns_33nslbW_U13->din1(grp_fu_752_p1);
    dft_mul_42ns_33nslbW_U13->ce(ap_var_for_const0);
    dft_mul_42ns_33nslbW_U13->dout(grp_fu_752_p2);
    dft_mul_64s_63ns_mb6_U14 = new dft_mul_64s_63ns_mb6<1,5,64,63,126>("dft_mul_64s_63ns_mb6_U14");
    dft_mul_64s_63ns_mb6_U14->clk(ap_clk);
    dft_mul_64s_63ns_mb6_U14->reset(ap_rst);
    dft_mul_64s_63ns_mb6_U14->din0(r_V_3_reg_1399);
    dft_mul_64s_63ns_mb6_U14->din1(grp_fu_853_p1);
    dft_mul_64s_63ns_mb6_U14->ce(ap_var_for_const0);
    dft_mul_64s_63ns_mb6_U14->dout(grp_fu_853_p2);
    dft_mux_164_1_1_1_U15 = new dft_mux_164_1_1_1<1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,1>("dft_mux_164_1_1_1_U15");
    dft_mux_164_1_1_1_U15->din0(ap_var_for_const1);
    dft_mux_164_1_1_1_U15->din1(ap_var_for_const1);
    dft_mux_164_1_1_1_U15->din2(ap_var_for_const1);
    dft_mux_164_1_1_1_U15->din3(ap_var_for_const2);
    dft_mux_164_1_1_1_U15->din4(ap_var_for_const2);
    dft_mux_164_1_1_1_U15->din5(ap_var_for_const2);
    dft_mux_164_1_1_1_U15->din6(ap_var_for_const2);
    dft_mux_164_1_1_1_U15->din7(ap_var_for_const1);
    dft_mux_164_1_1_1_U15->din8(ap_var_for_const1);
    dft_mux_164_1_1_1_U15->din9(ap_var_for_const2);
    dft_mux_164_1_1_1_U15->din10(ap_var_for_const2);
    dft_mux_164_1_1_1_U15->din11(ap_var_for_const2);
    dft_mux_164_1_1_1_U15->din12(ap_var_for_const2);
    dft_mux_164_1_1_1_U15->din13(ap_var_for_const1);
    dft_mux_164_1_1_1_U15->din14(ap_var_for_const1);
    dft_mux_164_1_1_1_U15->din15(ap_var_for_const1);
    dft_mux_164_1_1_1_U15->din16(p_Result_26_fu_912_p3);
    dft_mux_164_1_1_1_U15->dout(tmp_3_fu_918_p18);
    dft_mux_164_1_1_1_U16 = new dft_mux_164_1_1_1<1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,1>("dft_mux_164_1_1_1_U16");
    dft_mux_164_1_1_1_U16->din0(ap_var_for_const1);
    dft_mux_164_1_1_1_U16->din1(ap_var_for_const1);
    dft_mux_164_1_1_1_U16->din2(ap_var_for_const2);
    dft_mux_164_1_1_1_U16->din3(ap_var_for_const1);
    dft_mux_164_1_1_1_U16->din4(ap_var_for_const2);
    dft_mux_164_1_1_1_U16->din5(ap_var_for_const2);
    dft_mux_164_1_1_1_U16->din6(ap_var_for_const1);
    dft_mux_164_1_1_1_U16->din7(ap_var_for_const2);
    dft_mux_164_1_1_1_U16->din8(ap_var_for_const2);
    dft_mux_164_1_1_1_U16->din9(ap_var_for_const1);
    dft_mux_164_1_1_1_U16->din10(ap_var_for_const2);
    dft_mux_164_1_1_1_U16->din11(ap_var_for_const2);
    dft_mux_164_1_1_1_U16->din12(ap_var_for_const1);
    dft_mux_164_1_1_1_U16->din13(ap_var_for_const2);
    dft_mux_164_1_1_1_U16->din14(ap_var_for_const1);
    dft_mux_164_1_1_1_U16->din15(ap_var_for_const1);
    dft_mux_164_1_1_1_U16->din16(p_Result_26_fu_912_p3);
    dft_mux_164_1_1_1_U16->dout(tmp_4_fu_956_p18);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Ex_V_fu_507_p2);
    sensitive << ( storemerge_i_fu_440_p3 );
    sensitive << ( tmp_18_i_fu_503_p1 );

    SC_METHOD(thread_Mx_V_read_assign_fu_840_p3);
    sensitive << ( Mx_V_reg_1185 );
    sensitive << ( cos_basis_reg_1392 );

    SC_METHOD(thread_Mx_zeros_V_fu_480_p1);
    sensitive << ( tmp_i3_i_fu_472_p3 );

    SC_METHOD(thread_OP1_V_fu_617_p1);
    sensitive << ( tmp_i1_reg_1228 );

    SC_METHOD(thread_OP2_V_fu_661_p1);
    sensitive << ( tmp_25_i_reg_1274 );

    SC_METHOD(thread_addr_V_fu_312_p3);
    sensitive << ( closepath_fu_300_p2 );
    sensitive << ( expv_op_fu_306_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( p_Result_27_fu_1088_p4 );

    SC_METHOD(thread_closepath_fu_300_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( loc_V_fu_286_p4 );

    SC_METHOD(thread_cos_basis_fu_817_p0);
    sensitive << ( do_cos );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_cos_basis_fu_817_p3);
    sensitive << ( tmp_reg_1239 );
    sensitive << ( cos_basis_fu_817_p0 );
    sensitive << ( tmp_s_fu_812_p2 );

    SC_METHOD(thread_expv_op_fu_306_p2);
    sensitive << ( loc_V_fu_286_p4 );

    SC_METHOD(thread_fourth_order_double_4_address0);
    sensitive << ( tmp_30_i_reg_1257 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_fourth_order_double_4_ce0);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_fourth_order_double_5_address0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( tmp_30_i_fu_645_p1 );

    SC_METHOD(thread_fourth_order_double_5_ce0);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_fourth_order_double_6_address0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( tmp_30_i_fu_645_p1 );

    SC_METHOD(thread_fourth_order_double_6_ce0);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_fourth_order_double_7_address0);
    sensitive << ( tmp_30_i_reg_1257 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_fourth_order_double_7_ce0);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_fourth_order_double_s_address0);
    sensitive << ( tmp_30_i_reg_1257 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_fourth_order_double_s_ce0);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_grp_fu_372_p0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_fu_372_p00 );

    SC_METHOD(thread_grp_fu_372_p00);
    sensitive << ( ret_V_reg_1137 );

    SC_METHOD(thread_grp_fu_372_p1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_fu_372_p10 );

    SC_METHOD(thread_grp_fu_372_p10);
    sensitive << ( p_Result_20_fu_358_p3 );

    SC_METHOD(thread_grp_fu_620_p0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( OP1_V_fu_617_p1 );

    SC_METHOD(thread_grp_fu_620_p1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( OP1_V_fu_617_p1 );

    SC_METHOD(thread_grp_fu_664_p0);
    sensitive << ( OP2_V_fu_661_p1 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_grp_fu_664_p1);
    sensitive << ( OP1_V_reg_1245 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_grp_fu_669_p0);
    sensitive << ( OP2_V_fu_661_p1 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_grp_fu_669_p1);
    sensitive << ( OP2_V_fu_661_p1 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_grp_fu_681_p0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( grp_fu_681_p00 );

    SC_METHOD(thread_grp_fu_681_p00);
    sensitive << ( p_Val2_15_reg_1223 );

    SC_METHOD(thread_grp_fu_693_p0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( grp_fu_693_p00 );

    SC_METHOD(thread_grp_fu_693_p00);
    sensitive << ( tmp_25_i_reg_1274 );

    SC_METHOD(thread_grp_fu_752_p0);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( grp_fu_752_p00 );

    SC_METHOD(thread_grp_fu_752_p00);
    sensitive << ( tmp_27_i_reg_1332 );

    SC_METHOD(thread_grp_fu_752_p1);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( grp_fu_752_p10 );

    SC_METHOD(thread_grp_fu_752_p10);
    sensitive << ( fourth_order_double_14_reg_1357 );

    SC_METHOD(thread_grp_fu_853_p1);
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( grp_fu_853_p10 );

    SC_METHOD(thread_grp_fu_853_p10);
    sensitive << ( Mx_V_read_assign_fu_840_p3 );

    SC_METHOD(thread_grp_scaled_fixed2ieee_fu_268_ap_start);
    sensitive << ( grp_scaled_fixed2ieee_fu_268_ap_start_reg );

    SC_METHOD(thread_loc_V_1_fu_296_p1);
    sensitive << ( p_Val2_s_fu_274_p1 );

    SC_METHOD(thread_loc_V_2_fu_898_p4);
    sensitive << ( p_Val2_25_fu_887_p1 );

    SC_METHOD(thread_loc_V_3_fu_908_p1);
    sensitive << ( p_Val2_25_fu_887_p1 );

    SC_METHOD(thread_loc_V_fu_286_p4);
    sensitive << ( p_Val2_s_fu_274_p1 );

    SC_METHOD(thread_not_do_cos_i_fu_626_p0);
    sensitive << ( do_cos );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_not_do_cos_i_fu_626_p2);
    sensitive << ( not_do_cos_i_fu_626_p0 );

    SC_METHOD(thread_not_or_cond_demorgan_fu_1057_p2);
    sensitive << ( tmp_7_reg_1152 );
    sensitive << ( tmp_6_reg_1204 );

    SC_METHOD(thread_not_or_cond_fu_1061_p2);
    sensitive << ( not_or_cond_demorgan_fu_1057_p2 );

    SC_METHOD(thread_not_tmp_s_fu_1016_p2);
    sensitive << ( tmp_8_reg_1210 );

    SC_METHOD(thread_or_cond_fu_1001_p2);
    sensitive << ( tmp_7_reg_1152 );
    sensitive << ( tmp_6_reg_1204 );

    SC_METHOD(thread_p_Ex_V_ret_fu_859_p3);
    sensitive << ( Ex_V_reg_1192 );
    sensitive << ( cos_basis_reg_1392 );

    SC_METHOD(thread_p_Result_1_cast_fu_1067_p3);
    sensitive << ( not_or_cond_fu_1061_p2 );

    SC_METHOD(thread_p_Result_20_fu_358_p3);
    sensitive << ( loc_V_1_reg_1115 );

    SC_METHOD(thread_p_Result_21_fu_447_p3);
    sensitive << ( p_Result_i2_i_reg_1180 );

    SC_METHOD(thread_p_Result_22_fu_454_p4);
    sensitive << ( p_Result_21_fu_447_p3 );

    SC_METHOD(thread_p_Result_23_fu_464_p3);
    sensitive << ( p_Result_22_fu_454_p4 );

    SC_METHOD(thread_p_Result_24_fu_638_p3);
    sensitive << ( p_Result_i_reg_1218 );
    sensitive << ( sin_basis_fu_632_p2 );

    SC_METHOD(thread_p_Result_25_fu_890_p3);
    sensitive << ( p_Val2_25_fu_887_p1 );

    SC_METHOD(thread_p_Result_26_fu_912_p3);
    sensitive << ( p_Result_19_reg_1102 );
    sensitive << ( p_Val2_29_reg_1169 );

    SC_METHOD(thread_p_Result_27_fu_1088_p4);
    sensitive << ( p_Result_s_41_fu_1041_p3 );
    sensitive << ( ret_V_6_fu_1049_p3 );
    sensitive << ( ret_V_7_fu_1080_p3 );

    SC_METHOD(thread_p_Result_i_i_fu_320_p4);
    sensitive << ( addr_V_fu_312_p3 );

    SC_METHOD(thread_p_Result_s_39_fu_1026_p3);
    sensitive << ( tmp_9_fu_1021_p2 );
    sensitive << ( not_tmp_s_fu_1016_p2 );
    sensitive << ( p_Result_25_fu_890_p3 );

    SC_METHOD(thread_p_Result_s_40_fu_1034_p3);
    sensitive << ( tmp_8_reg_1210 );
    sensitive << ( loc_V_2_fu_898_p4 );

    SC_METHOD(thread_p_Result_s_41_fu_1041_p3);
    sensitive << ( or_cond_fu_1001_p2 );
    sensitive << ( p_Result_s_fu_1005_p2 );
    sensitive << ( p_Result_s_39_fu_1026_p3 );

    SC_METHOD(thread_p_Result_s_fu_1005_p2);
    sensitive << ( p_Result_19_reg_1102 );
    sensitive << ( not_do_cos_i_reg_1252 );

    SC_METHOD(thread_p_Val2_11_fu_418_p3);
    sensitive << ( p_Val2_8_reg_1158 );
    sensitive << ( tmp_14_fu_409_p1 );
    sensitive << ( p_Val2_i_fu_413_p2 );

    SC_METHOD(thread_p_Val2_13_fu_488_p2);
    sensitive << ( p_Val2_11_reg_1175 );
    sensitive << ( tmp_15_i_fu_484_p1 );

    SC_METHOD(thread_p_Val2_14_fu_565_p3);
    sensitive << ( isNeg_reg_1198 );
    sensitive << ( tmp_22_i_fu_555_p2 );
    sensitive << ( tmp_23_i_fu_560_p2 );

    SC_METHOD(thread_p_Val2_15_fu_582_p1);
    sensitive << ( p_Val2_14_fu_565_p3 );

    SC_METHOD(thread_p_Val2_20_fu_739_p3);
    sensitive << ( p_Val2_19_reg_1342 );

    SC_METHOD(thread_p_Val2_21_fu_787_p2);
    sensitive << ( tmp_32_i_fu_780_p1 );
    sensitive << ( tmp_33_i_fu_784_p1 );

    SC_METHOD(thread_p_Val2_22_fu_796_p2);
    sensitive << ( p_Val2_21_fu_787_p2 );
    sensitive << ( tmp_35_i_cast_fu_793_p1 );

    SC_METHOD(thread_p_Val2_23_fu_826_p2);
    sensitive << ( p_Val2_22_reg_1382 );
    sensitive << ( tmp_37_i_cast_fu_823_p1 );

    SC_METHOD(thread_p_Val2_25_fu_887_p1);
    sensitive << ( resultf_reg_1424 );

    SC_METHOD(thread_p_Val2_29_fu_403_p3);
    sensitive << ( closepath_reg_1121 );
    sensitive << ( tmp_14_i_reg_1164 );

    SC_METHOD(thread_p_Val2_4_fu_764_p0);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( p_Val2_4_fu_764_p00 );

    SC_METHOD(thread_p_Val2_4_fu_764_p00);
    sensitive << ( tmp_29_i_reg_1337 );

    SC_METHOD(thread_p_Val2_4_fu_764_p1);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( p_Val2_4_fu_764_p10 );

    SC_METHOD(thread_p_Val2_4_fu_764_p10);
    sensitive << ( fourth_order_double_16_reg_1362 );

    SC_METHOD(thread_p_Val2_4_fu_764_p2);
    sensitive << ( p_Val2_4_fu_764_p0 );
    sensitive << ( p_Val2_4_fu_764_p1 );

    SC_METHOD(thread_p_Val2_i_fu_413_p2);
    sensitive << ( p_Val2_8_reg_1158 );

    SC_METHOD(thread_p_Val2_s_fu_274_p1);
    sensitive << ( t_in );

    SC_METHOD(thread_p_cast_cast_fu_1009_p0);
    sensitive << ( do_cos );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_p_cast_cast_fu_1009_p3);
    sensitive << ( p_cast_cast_fu_1009_p0 );

    SC_METHOD(thread_r_V_3_fu_834_p2);
    sensitive << ( p_Val2_23_fu_826_p2 );
    sensitive << ( tmp_39_i_cast_fu_831_p1 );

    SC_METHOD(thread_r_V_4_fu_342_p2);
    sensitive << ( ref_4oPi_table_256_V_q0 );
    sensitive << ( tmp_4_i_i_fu_339_p1 );

    SC_METHOD(thread_r_V_fu_880_p2);
    sensitive << ( rhs_V_fu_876_p1 );

    SC_METHOD(thread_ref_4oPi_table_256_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_2_i_i_fu_330_p1 );

    SC_METHOD(thread_ref_4oPi_table_256_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ret_V_6_fu_1049_p3);
    sensitive << ( or_cond_fu_1001_p2 );
    sensitive << ( p_cast_cast_fu_1009_p3 );
    sensitive << ( p_Result_s_40_fu_1034_p3 );

    SC_METHOD(thread_ret_V_7_fu_1080_p3);
    sensitive << ( tmp_10_fu_1075_p2 );
    sensitive << ( p_Result_1_cast_fu_1067_p3 );
    sensitive << ( loc_V_3_fu_908_p1 );

    SC_METHOD(thread_rhs_V_fu_876_p1);
    sensitive << ( p_Ex_V_ret_fu_859_p3 );

    SC_METHOD(thread_sh_assign_2_cast_fu_547_p1);
    sensitive << ( sh_assign_fu_540_p3 );

    SC_METHOD(thread_sh_assign_fu_540_p3);
    sensitive << ( isNeg_reg_1198 );
    sensitive << ( sh_cast_fu_531_p1 );
    sensitive << ( tmp_20_i_fu_534_p2 );

    SC_METHOD(thread_sh_cast_fu_531_p1);
    sensitive << ( Ex_V_reg_1192 );

    SC_METHOD(thread_sin_basis_fu_632_p2);
    sensitive << ( tmp_fu_596_p10 );
    sensitive << ( not_do_cos_i_fu_626_p2 );

    SC_METHOD(thread_storemerge_i_fu_440_p3);
    sensitive << ( closepath_reg_1121 );
    sensitive << ( tmp_i_fu_435_p2 );

    SC_METHOD(thread_tmp_10_fu_1075_p2);
    sensitive << ( tmp_8_reg_1210 );
    sensitive << ( or_cond_fu_1001_p2 );

    SC_METHOD(thread_tmp_13_fu_335_p1);
    sensitive << ( addr_V_fu_312_p3 );

    SC_METHOD(thread_tmp_14_fu_409_p1);
    sensitive << ( p_Val2_29_fu_403_p3 );

    SC_METHOD(thread_tmp_15_i_fu_484_p1);
    sensitive << ( Mx_zeros_V_fu_480_p1 );

    SC_METHOD(thread_tmp_18_i_fu_503_p1);
    sensitive << ( Mx_zeros_V_fu_480_p1 );

    SC_METHOD(thread_tmp_20_i_fu_534_p2);
    sensitive << ( sh_cast_fu_531_p1 );

    SC_METHOD(thread_tmp_21_i_fu_551_p1);
    sensitive << ( sh_assign_2_cast_fu_547_p1 );

    SC_METHOD(thread_tmp_22_i_fu_555_p2);
    sensitive << ( Mx_V_reg_1185 );
    sensitive << ( tmp_21_i_fu_551_p1 );

    SC_METHOD(thread_tmp_23_i_fu_560_p2);
    sensitive << ( Mx_V_reg_1185 );
    sensitive << ( tmp_21_i_fu_551_p1 );

    SC_METHOD(thread_tmp_2_i_i_fu_330_p1);
    sensitive << ( p_Result_i_i_fu_320_p4 );

    SC_METHOD(thread_tmp_30_i_fu_645_p1);
    sensitive << ( p_Result_24_fu_638_p3 );

    SC_METHOD(thread_tmp_32_i_fu_780_p1);
    sensitive << ( p_Val2_20_fu_739_p3 );

    SC_METHOD(thread_tmp_33_i_fu_784_p1);
    sensitive << ( tmp_12_i_reg_1347 );

    SC_METHOD(thread_tmp_35_i_cast_fu_793_p1);
    sensitive << ( tmp_14_i1_reg_1352 );

    SC_METHOD(thread_tmp_37_i_cast_fu_823_p1);
    sensitive << ( tmp_1_reg_1387 );

    SC_METHOD(thread_tmp_39_i_cast_fu_831_p1);
    sensitive << ( tmp_2_reg_1377 );

    SC_METHOD(thread_tmp_4_i_i_fu_339_p1);
    sensitive << ( tmp_13_reg_1132 );

    SC_METHOD(thread_tmp_5_fu_994_p3);
    sensitive << ( cos_basis_reg_1392 );
    sensitive << ( tmp_3_fu_918_p18 );
    sensitive << ( tmp_4_fu_956_p18 );

    SC_METHOD(thread_tmp_6_fu_521_p2);
    sensitive << ( loc_V_reg_1108 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_tmp_7_fu_378_p2);
    sensitive << ( loc_V_1_reg_1115 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_tmp_8_fu_526_p2);
    sensitive << ( loc_V_reg_1108 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_tmp_9_fu_1021_p2);
    sensitive << ( tmp_8_reg_1210 );
    sensitive << ( tmp_5_fu_994_p3 );

    SC_METHOD(thread_tmp_i3_i_fu_472_p3);
    sensitive << ( p_Result_23_fu_464_p3 );

    SC_METHOD(thread_tmp_i_fu_435_p2);
    sensitive << ( loc_V_reg_1108 );

    SC_METHOD(thread_tmp_s_fu_812_p2);
    sensitive << ( tmp_reg_1239 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( grp_scaled_fixed2ieee_fu_268_ap_done );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    ap_CS_fsm = "000000000000000000000001";
    grp_scaled_fixed2ieee_fu_268_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sin_or_cos_double_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, t_in, "(port)t_in");
    sc_trace(mVcdFile, do_cos, "(port)do_cos");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ref_4oPi_table_256_V_address0, "ref_4oPi_table_256_V_address0");
    sc_trace(mVcdFile, ref_4oPi_table_256_V_ce0, "ref_4oPi_table_256_V_ce0");
    sc_trace(mVcdFile, ref_4oPi_table_256_V_q0, "ref_4oPi_table_256_V_q0");
    sc_trace(mVcdFile, fourth_order_double_4_address0, "fourth_order_double_4_address0");
    sc_trace(mVcdFile, fourth_order_double_4_ce0, "fourth_order_double_4_ce0");
    sc_trace(mVcdFile, fourth_order_double_4_q0, "fourth_order_double_4_q0");
    sc_trace(mVcdFile, fourth_order_double_5_address0, "fourth_order_double_5_address0");
    sc_trace(mVcdFile, fourth_order_double_5_ce0, "fourth_order_double_5_ce0");
    sc_trace(mVcdFile, fourth_order_double_5_q0, "fourth_order_double_5_q0");
    sc_trace(mVcdFile, fourth_order_double_6_address0, "fourth_order_double_6_address0");
    sc_trace(mVcdFile, fourth_order_double_6_ce0, "fourth_order_double_6_ce0");
    sc_trace(mVcdFile, fourth_order_double_6_q0, "fourth_order_double_6_q0");
    sc_trace(mVcdFile, fourth_order_double_7_address0, "fourth_order_double_7_address0");
    sc_trace(mVcdFile, fourth_order_double_7_ce0, "fourth_order_double_7_ce0");
    sc_trace(mVcdFile, fourth_order_double_7_q0, "fourth_order_double_7_q0");
    sc_trace(mVcdFile, fourth_order_double_s_address0, "fourth_order_double_s_address0");
    sc_trace(mVcdFile, fourth_order_double_s_ce0, "fourth_order_double_s_ce0");
    sc_trace(mVcdFile, fourth_order_double_s_q0, "fourth_order_double_s_q0");
    sc_trace(mVcdFile, p_Result_19_reg_1102, "p_Result_19_reg_1102");
    sc_trace(mVcdFile, loc_V_fu_286_p4, "loc_V_fu_286_p4");
    sc_trace(mVcdFile, loc_V_reg_1108, "loc_V_reg_1108");
    sc_trace(mVcdFile, loc_V_1_fu_296_p1, "loc_V_1_fu_296_p1");
    sc_trace(mVcdFile, loc_V_1_reg_1115, "loc_V_1_reg_1115");
    sc_trace(mVcdFile, closepath_fu_300_p2, "closepath_fu_300_p2");
    sc_trace(mVcdFile, closepath_reg_1121, "closepath_reg_1121");
    sc_trace(mVcdFile, tmp_13_fu_335_p1, "tmp_13_fu_335_p1");
    sc_trace(mVcdFile, tmp_13_reg_1132, "tmp_13_reg_1132");
    sc_trace(mVcdFile, ret_V_reg_1137, "ret_V_reg_1137");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_7_fu_378_p2, "tmp_7_fu_378_p2");
    sc_trace(mVcdFile, tmp_7_reg_1152, "tmp_7_reg_1152");
    sc_trace(mVcdFile, p_Val2_8_reg_1158, "p_Val2_8_reg_1158");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_14_i_reg_1164, "tmp_14_i_reg_1164");
    sc_trace(mVcdFile, p_Val2_29_fu_403_p3, "p_Val2_29_fu_403_p3");
    sc_trace(mVcdFile, p_Val2_29_reg_1169, "p_Val2_29_reg_1169");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, p_Val2_11_fu_418_p3, "p_Val2_11_fu_418_p3");
    sc_trace(mVcdFile, p_Val2_11_reg_1175, "p_Val2_11_reg_1175");
    sc_trace(mVcdFile, p_Result_i2_i_reg_1180, "p_Result_i2_i_reg_1180");
    sc_trace(mVcdFile, Mx_V_reg_1185, "Mx_V_reg_1185");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, Ex_V_fu_507_p2, "Ex_V_fu_507_p2");
    sc_trace(mVcdFile, Ex_V_reg_1192, "Ex_V_reg_1192");
    sc_trace(mVcdFile, isNeg_reg_1198, "isNeg_reg_1198");
    sc_trace(mVcdFile, tmp_6_fu_521_p2, "tmp_6_fu_521_p2");
    sc_trace(mVcdFile, tmp_6_reg_1204, "tmp_6_reg_1204");
    sc_trace(mVcdFile, tmp_8_fu_526_p2, "tmp_8_fu_526_p2");
    sc_trace(mVcdFile, tmp_8_reg_1210, "tmp_8_reg_1210");
    sc_trace(mVcdFile, p_Result_i_reg_1218, "p_Result_i_reg_1218");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, p_Val2_15_fu_582_p1, "p_Val2_15_fu_582_p1");
    sc_trace(mVcdFile, p_Val2_15_reg_1223, "p_Val2_15_reg_1223");
    sc_trace(mVcdFile, tmp_i1_reg_1228, "tmp_i1_reg_1228");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, tmp_fu_596_p10, "tmp_fu_596_p10");
    sc_trace(mVcdFile, tmp_reg_1239, "tmp_reg_1239");
    sc_trace(mVcdFile, OP1_V_fu_617_p1, "OP1_V_fu_617_p1");
    sc_trace(mVcdFile, OP1_V_reg_1245, "OP1_V_reg_1245");
    sc_trace(mVcdFile, not_do_cos_i_fu_626_p2, "not_do_cos_i_fu_626_p2");
    sc_trace(mVcdFile, not_do_cos_i_reg_1252, "not_do_cos_i_reg_1252");
    sc_trace(mVcdFile, tmp_30_i_fu_645_p1, "tmp_30_i_fu_645_p1");
    sc_trace(mVcdFile, tmp_30_i_reg_1257, "tmp_30_i_reg_1257");
    sc_trace(mVcdFile, tmp_25_i_reg_1274, "tmp_25_i_reg_1274");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, fourth_order_double_10_reg_1280, "fourth_order_double_10_reg_1280");
    sc_trace(mVcdFile, fourth_order_double_12_reg_1285, "fourth_order_double_12_reg_1285");
    sc_trace(mVcdFile, OP2_V_fu_661_p1, "OP2_V_fu_661_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, tmp_27_i_reg_1332, "tmp_27_i_reg_1332");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, tmp_29_i_reg_1337, "tmp_29_i_reg_1337");
    sc_trace(mVcdFile, p_Val2_19_reg_1342, "p_Val2_19_reg_1342");
    sc_trace(mVcdFile, tmp_12_i_reg_1347, "tmp_12_i_reg_1347");
    sc_trace(mVcdFile, tmp_14_i1_reg_1352, "tmp_14_i1_reg_1352");
    sc_trace(mVcdFile, fourth_order_double_14_reg_1357, "fourth_order_double_14_reg_1357");
    sc_trace(mVcdFile, fourth_order_double_16_reg_1362, "fourth_order_double_16_reg_1362");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, tmp_2_reg_1377, "tmp_2_reg_1377");
    sc_trace(mVcdFile, p_Val2_22_fu_796_p2, "p_Val2_22_fu_796_p2");
    sc_trace(mVcdFile, p_Val2_22_reg_1382, "p_Val2_22_reg_1382");
    sc_trace(mVcdFile, tmp_1_reg_1387, "tmp_1_reg_1387");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, cos_basis_fu_817_p3, "cos_basis_fu_817_p3");
    sc_trace(mVcdFile, cos_basis_reg_1392, "cos_basis_reg_1392");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, r_V_3_fu_834_p2, "r_V_3_fu_834_p2");
    sc_trace(mVcdFile, r_V_3_reg_1399, "r_V_3_reg_1399");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, result_V_reg_1414, "result_V_reg_1414");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, r_V_fu_880_p2, "r_V_fu_880_p2");
    sc_trace(mVcdFile, r_V_reg_1419, "r_V_reg_1419");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_268_ap_return, "grp_scaled_fixed2ieee_fu_268_ap_return");
    sc_trace(mVcdFile, resultf_reg_1424, "resultf_reg_1424");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_268_ap_idle, "grp_scaled_fixed2ieee_fu_268_ap_idle");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_268_ap_ready, "grp_scaled_fixed2ieee_fu_268_ap_ready");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_268_ap_done, "grp_scaled_fixed2ieee_fu_268_ap_done");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_268_ap_start, "grp_scaled_fixed2ieee_fu_268_ap_start");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_268_ap_start_reg, "grp_scaled_fixed2ieee_fu_268_ap_start_reg");
    sc_trace(mVcdFile, tmp_2_i_i_fu_330_p1, "tmp_2_i_i_fu_330_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_274_p1, "p_Val2_s_fu_274_p1");
    sc_trace(mVcdFile, expv_op_fu_306_p2, "expv_op_fu_306_p2");
    sc_trace(mVcdFile, addr_V_fu_312_p3, "addr_V_fu_312_p3");
    sc_trace(mVcdFile, p_Result_i_i_fu_320_p4, "p_Result_i_i_fu_320_p4");
    sc_trace(mVcdFile, tmp_4_i_i_fu_339_p1, "tmp_4_i_i_fu_339_p1");
    sc_trace(mVcdFile, r_V_4_fu_342_p2, "r_V_4_fu_342_p2");
    sc_trace(mVcdFile, p_Result_20_fu_358_p3, "p_Result_20_fu_358_p3");
    sc_trace(mVcdFile, grp_fu_372_p0, "grp_fu_372_p0");
    sc_trace(mVcdFile, grp_fu_372_p1, "grp_fu_372_p1");
    sc_trace(mVcdFile, grp_fu_372_p2, "grp_fu_372_p2");
    sc_trace(mVcdFile, tmp_14_fu_409_p1, "tmp_14_fu_409_p1");
    sc_trace(mVcdFile, p_Val2_i_fu_413_p2, "p_Val2_i_fu_413_p2");
    sc_trace(mVcdFile, tmp_i_fu_435_p2, "tmp_i_fu_435_p2");
    sc_trace(mVcdFile, p_Result_21_fu_447_p3, "p_Result_21_fu_447_p3");
    sc_trace(mVcdFile, p_Result_22_fu_454_p4, "p_Result_22_fu_454_p4");
    sc_trace(mVcdFile, p_Result_23_fu_464_p3, "p_Result_23_fu_464_p3");
    sc_trace(mVcdFile, tmp_i3_i_fu_472_p3, "tmp_i3_i_fu_472_p3");
    sc_trace(mVcdFile, Mx_zeros_V_fu_480_p1, "Mx_zeros_V_fu_480_p1");
    sc_trace(mVcdFile, tmp_15_i_fu_484_p1, "tmp_15_i_fu_484_p1");
    sc_trace(mVcdFile, p_Val2_13_fu_488_p2, "p_Val2_13_fu_488_p2");
    sc_trace(mVcdFile, storemerge_i_fu_440_p3, "storemerge_i_fu_440_p3");
    sc_trace(mVcdFile, tmp_18_i_fu_503_p1, "tmp_18_i_fu_503_p1");
    sc_trace(mVcdFile, sh_cast_fu_531_p1, "sh_cast_fu_531_p1");
    sc_trace(mVcdFile, tmp_20_i_fu_534_p2, "tmp_20_i_fu_534_p2");
    sc_trace(mVcdFile, sh_assign_fu_540_p3, "sh_assign_fu_540_p3");
    sc_trace(mVcdFile, sh_assign_2_cast_fu_547_p1, "sh_assign_2_cast_fu_547_p1");
    sc_trace(mVcdFile, tmp_21_i_fu_551_p1, "tmp_21_i_fu_551_p1");
    sc_trace(mVcdFile, tmp_22_i_fu_555_p2, "tmp_22_i_fu_555_p2");
    sc_trace(mVcdFile, tmp_23_i_fu_560_p2, "tmp_23_i_fu_560_p2");
    sc_trace(mVcdFile, p_Val2_14_fu_565_p3, "p_Val2_14_fu_565_p3");
    sc_trace(mVcdFile, grp_fu_620_p0, "grp_fu_620_p0");
    sc_trace(mVcdFile, grp_fu_620_p1, "grp_fu_620_p1");
    sc_trace(mVcdFile, not_do_cos_i_fu_626_p0, "not_do_cos_i_fu_626_p0");
    sc_trace(mVcdFile, sin_basis_fu_632_p2, "sin_basis_fu_632_p2");
    sc_trace(mVcdFile, p_Result_24_fu_638_p3, "p_Result_24_fu_638_p3");
    sc_trace(mVcdFile, grp_fu_620_p2, "grp_fu_620_p2");
    sc_trace(mVcdFile, grp_fu_664_p0, "grp_fu_664_p0");
    sc_trace(mVcdFile, grp_fu_664_p1, "grp_fu_664_p1");
    sc_trace(mVcdFile, grp_fu_669_p0, "grp_fu_669_p0");
    sc_trace(mVcdFile, grp_fu_669_p1, "grp_fu_669_p1");
    sc_trace(mVcdFile, grp_fu_681_p0, "grp_fu_681_p0");
    sc_trace(mVcdFile, grp_fu_693_p0, "grp_fu_693_p0");
    sc_trace(mVcdFile, grp_fu_664_p2, "grp_fu_664_p2");
    sc_trace(mVcdFile, grp_fu_669_p2, "grp_fu_669_p2");
    sc_trace(mVcdFile, grp_fu_681_p2, "grp_fu_681_p2");
    sc_trace(mVcdFile, grp_fu_693_p2, "grp_fu_693_p2");
    sc_trace(mVcdFile, grp_fu_752_p0, "grp_fu_752_p0");
    sc_trace(mVcdFile, grp_fu_752_p1, "grp_fu_752_p1");
    sc_trace(mVcdFile, p_Val2_4_fu_764_p0, "p_Val2_4_fu_764_p0");
    sc_trace(mVcdFile, p_Val2_4_fu_764_p1, "p_Val2_4_fu_764_p1");
    sc_trace(mVcdFile, p_Val2_4_fu_764_p2, "p_Val2_4_fu_764_p2");
    sc_trace(mVcdFile, p_Val2_20_fu_739_p3, "p_Val2_20_fu_739_p3");
    sc_trace(mVcdFile, tmp_32_i_fu_780_p1, "tmp_32_i_fu_780_p1");
    sc_trace(mVcdFile, tmp_33_i_fu_784_p1, "tmp_33_i_fu_784_p1");
    sc_trace(mVcdFile, p_Val2_21_fu_787_p2, "p_Val2_21_fu_787_p2");
    sc_trace(mVcdFile, tmp_35_i_cast_fu_793_p1, "tmp_35_i_cast_fu_793_p1");
    sc_trace(mVcdFile, grp_fu_752_p2, "grp_fu_752_p2");
    sc_trace(mVcdFile, cos_basis_fu_817_p0, "cos_basis_fu_817_p0");
    sc_trace(mVcdFile, tmp_s_fu_812_p2, "tmp_s_fu_812_p2");
    sc_trace(mVcdFile, tmp_37_i_cast_fu_823_p1, "tmp_37_i_cast_fu_823_p1");
    sc_trace(mVcdFile, p_Val2_23_fu_826_p2, "p_Val2_23_fu_826_p2");
    sc_trace(mVcdFile, tmp_39_i_cast_fu_831_p1, "tmp_39_i_cast_fu_831_p1");
    sc_trace(mVcdFile, Mx_V_read_assign_fu_840_p3, "Mx_V_read_assign_fu_840_p3");
    sc_trace(mVcdFile, grp_fu_853_p1, "grp_fu_853_p1");
    sc_trace(mVcdFile, grp_fu_853_p2, "grp_fu_853_p2");
    sc_trace(mVcdFile, p_Ex_V_ret_fu_859_p3, "p_Ex_V_ret_fu_859_p3");
    sc_trace(mVcdFile, rhs_V_fu_876_p1, "rhs_V_fu_876_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, p_Val2_25_fu_887_p1, "p_Val2_25_fu_887_p1");
    sc_trace(mVcdFile, p_Result_26_fu_912_p3, "p_Result_26_fu_912_p3");
    sc_trace(mVcdFile, tmp_3_fu_918_p18, "tmp_3_fu_918_p18");
    sc_trace(mVcdFile, tmp_4_fu_956_p18, "tmp_4_fu_956_p18");
    sc_trace(mVcdFile, p_cast_cast_fu_1009_p0, "p_cast_cast_fu_1009_p0");
    sc_trace(mVcdFile, tmp_5_fu_994_p3, "tmp_5_fu_994_p3");
    sc_trace(mVcdFile, tmp_9_fu_1021_p2, "tmp_9_fu_1021_p2");
    sc_trace(mVcdFile, not_tmp_s_fu_1016_p2, "not_tmp_s_fu_1016_p2");
    sc_trace(mVcdFile, p_Result_25_fu_890_p3, "p_Result_25_fu_890_p3");
    sc_trace(mVcdFile, loc_V_2_fu_898_p4, "loc_V_2_fu_898_p4");
    sc_trace(mVcdFile, or_cond_fu_1001_p2, "or_cond_fu_1001_p2");
    sc_trace(mVcdFile, p_Result_s_fu_1005_p2, "p_Result_s_fu_1005_p2");
    sc_trace(mVcdFile, p_Result_s_39_fu_1026_p3, "p_Result_s_39_fu_1026_p3");
    sc_trace(mVcdFile, p_cast_cast_fu_1009_p3, "p_cast_cast_fu_1009_p3");
    sc_trace(mVcdFile, p_Result_s_40_fu_1034_p3, "p_Result_s_40_fu_1034_p3");
    sc_trace(mVcdFile, not_or_cond_demorgan_fu_1057_p2, "not_or_cond_demorgan_fu_1057_p2");
    sc_trace(mVcdFile, not_or_cond_fu_1061_p2, "not_or_cond_fu_1061_p2");
    sc_trace(mVcdFile, tmp_10_fu_1075_p2, "tmp_10_fu_1075_p2");
    sc_trace(mVcdFile, p_Result_1_cast_fu_1067_p3, "p_Result_1_cast_fu_1067_p3");
    sc_trace(mVcdFile, loc_V_3_fu_908_p1, "loc_V_3_fu_908_p1");
    sc_trace(mVcdFile, p_Result_s_41_fu_1041_p3, "p_Result_s_41_fu_1041_p3");
    sc_trace(mVcdFile, ret_V_6_fu_1049_p3, "ret_V_6_fu_1049_p3");
    sc_trace(mVcdFile, ret_V_7_fu_1080_p3, "ret_V_7_fu_1080_p3");
    sc_trace(mVcdFile, p_Result_27_fu_1088_p4, "p_Result_27_fu_1088_p4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_372_p00, "grp_fu_372_p00");
    sc_trace(mVcdFile, grp_fu_372_p10, "grp_fu_372_p10");
    sc_trace(mVcdFile, grp_fu_681_p00, "grp_fu_681_p00");
    sc_trace(mVcdFile, grp_fu_693_p00, "grp_fu_693_p00");
    sc_trace(mVcdFile, grp_fu_752_p00, "grp_fu_752_p00");
    sc_trace(mVcdFile, grp_fu_752_p10, "grp_fu_752_p10");
    sc_trace(mVcdFile, grp_fu_853_p10, "grp_fu_853_p10");
    sc_trace(mVcdFile, p_Val2_4_fu_764_p00, "p_Val2_4_fu_764_p00");
    sc_trace(mVcdFile, p_Val2_4_fu_764_p10, "p_Val2_4_fu_764_p10");
#endif

    }
}

sin_or_cos_double_s::~sin_or_cos_double_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete ref_4oPi_table_256_V_U;
    delete fourth_order_double_4_U;
    delete fourth_order_double_5_U;
    delete fourth_order_double_6_U;
    delete fourth_order_double_7_U;
    delete fourth_order_double_s_U;
    delete grp_scaled_fixed2ieee_fu_268;
    delete dft_mul_170ns_53nhbi_U6;
    delete dft_mux_83_1_1_1_U7;
    delete dft_mul_49ns_49nsibs_U8;
    delete dft_mul_49ns_49nsibs_U9;
    delete dft_mul_49ns_49nsibs_U10;
    delete dft_mul_56ns_52s_jbC_U11;
    delete dft_mul_49ns_44s_kbM_U12;
    delete dft_mul_42ns_33nslbW_U13;
    delete dft_mul_64s_63ns_mb6_U14;
    delete dft_mux_164_1_1_1_U15;
    delete dft_mux_164_1_1_1_U16;
}

void sin_or_cos_double_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void sin_or_cos_double_s::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv1_0;
}

void sin_or_cos_double_s::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv1_1;
}

void sin_or_cos_double_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_scaled_fixed2ieee_fu_268_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
            grp_scaled_fixed2ieee_fu_268_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_scaled_fixed2ieee_fu_268_ap_ready.read())) {
            grp_scaled_fixed2ieee_fu_268_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        Ex_V_reg_1192 = Ex_V_fu_507_p2.read();
        Mx_V_reg_1185 = p_Val2_13_fu_488_p2.read().range(123, 61);
        isNeg_reg_1198 = Ex_V_fu_507_p2.read().range(10, 10);
        tmp_6_reg_1204 = tmp_6_fu_521_p2.read();
        tmp_8_reg_1210 = tmp_8_fu_526_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        OP1_V_reg_1245 = OP1_V_fu_617_p1.read();
        not_do_cos_i_reg_1252 = not_do_cos_i_fu_626_p2.read();
        tmp_30_i_reg_1257 = tmp_30_i_fu_645_p1.read();
        tmp_reg_1239 = tmp_fu_596_p10.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        closepath_reg_1121 = closepath_fu_300_p2.read();
        loc_V_1_reg_1115 = loc_V_1_fu_296_p1.read();
        loc_V_reg_1108 = p_Val2_s_fu_274_p1.read().range(62, 52);
        p_Result_19_reg_1102 = p_Val2_s_fu_274_p1.read().range(63, 63);
        tmp_13_reg_1132 = tmp_13_fu_335_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        cos_basis_reg_1392 = cos_basis_fu_817_p3.read();
        r_V_3_reg_1399 = r_V_3_fu_834_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        fourth_order_double_10_reg_1280 = fourth_order_double_5_q0.read();
        fourth_order_double_12_reg_1285 = fourth_order_double_6_q0.read();
        tmp_25_i_reg_1274 = grp_fu_620_p2.read().range(97, 49);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        fourth_order_double_14_reg_1357 = fourth_order_double_7_q0.read();
        fourth_order_double_16_reg_1362 = fourth_order_double_s_q0.read();
        p_Val2_19_reg_1342 = fourth_order_double_4_q0.read();
        tmp_12_i_reg_1347 = grp_fu_681_p2.read().range(107, 52);
        tmp_14_i1_reg_1352 = grp_fu_693_p2.read().range(92, 45);
        tmp_27_i_reg_1332 = grp_fu_664_p2.read().range(97, 56);
        tmp_29_i_reg_1337 = grp_fu_669_p2.read().range(97, 63);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        p_Result_i2_i_reg_1180 = p_Val2_11_fu_418_p3.read().range(123, 63);
        p_Val2_11_reg_1175 = p_Val2_11_fu_418_p3.read();
        p_Val2_29_reg_1169 = p_Val2_29_fu_403_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        p_Result_i_reg_1218 = p_Val2_14_fu_565_p3.read().range(62, 56);
        p_Val2_15_reg_1223 = p_Val2_15_fu_582_p1.read();
        tmp_i1_reg_1228 = p_Val2_14_fu_565_p3.read().range(55, 7);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        p_Val2_22_reg_1382 = p_Val2_22_fu_796_p2.read();
        tmp_2_reg_1377 = p_Val2_4_fu_764_p2.read().range(59, 31);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        p_Val2_8_reg_1158 = grp_fu_372_p2.read().range(166, 43);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        r_V_reg_1419 = r_V_fu_880_p2.read();
        result_V_reg_1414 = grp_fu_853_p2.read().range(125, 63);
    }
    if ((esl_seteq<1,1,1>(grp_scaled_fixed2ieee_fu_268_ap_done.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()))) {
        resultf_reg_1424 = grp_scaled_fixed2ieee_fu_268_ap_return.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        ret_V_reg_1137 = r_V_4_fu_342_p2.read().range(255, 86);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(closepath_reg_1121.read(), ap_const_lv1_0))) {
        tmp_14_i_reg_1164 = grp_fu_372_p2.read().range(169, 167);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        tmp_1_reg_1387 = grp_fu_752_p2.read().range(74, 38);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        tmp_7_reg_1152 = tmp_7_fu_378_p2.read();
    }
}

void sin_or_cos_double_s::thread_Ex_V_fu_507_p2() {
    Ex_V_fu_507_p2 = (!storemerge_i_fu_440_p3.read().is_01() || !tmp_18_i_fu_503_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(storemerge_i_fu_440_p3.read()) - sc_biguint<11>(tmp_18_i_fu_503_p1.read()));
}

void sin_or_cos_double_s::thread_Mx_V_read_assign_fu_840_p3() {
    Mx_V_read_assign_fu_840_p3 = (!cos_basis_reg_1392.read()[0].is_01())? sc_lv<63>(): ((cos_basis_reg_1392.read()[0].to_bool())? ap_const_lv63_7FFFFFFFFFFFFFFF: Mx_V_reg_1185.read());
}

void sin_or_cos_double_s::thread_Mx_zeros_V_fu_480_p1() {
    Mx_zeros_V_fu_480_p1 = tmp_i3_i_fu_472_p3.read().range(6-1, 0);
}

void sin_or_cos_double_s::thread_OP1_V_fu_617_p1() {
    OP1_V_fu_617_p1 = esl_zext<98,49>(tmp_i1_reg_1228.read());
}

void sin_or_cos_double_s::thread_OP2_V_fu_661_p1() {
    OP2_V_fu_661_p1 = esl_zext<98,49>(tmp_25_i_reg_1274.read());
}

void sin_or_cos_double_s::thread_addr_V_fu_312_p3() {
    addr_V_fu_312_p3 = (!closepath_fu_300_p2.read()[0].is_01())? sc_lv<11>(): ((closepath_fu_300_p2.read()[0].to_bool())? ap_const_lv11_4A: expv_op_fu_306_p2.read());
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void sin_or_cos_double_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_ap_return() {
    ap_return = p_Result_27_fu_1088_p4.read();
}

void sin_or_cos_double_s::thread_closepath_fu_300_p2() {
    closepath_fu_300_p2 = (!loc_V_fu_286_p4.read().is_01() || !ap_const_lv11_3FE.is_01())? sc_lv<1>(): (sc_biguint<11>(loc_V_fu_286_p4.read()) < sc_biguint<11>(ap_const_lv11_3FE));
}

void sin_or_cos_double_s::thread_cos_basis_fu_817_p0() {
    cos_basis_fu_817_p0 =  (sc_lv<1>) (do_cos.read());
}

void sin_or_cos_double_s::thread_cos_basis_fu_817_p3() {
    cos_basis_fu_817_p3 = (!cos_basis_fu_817_p0.read()[0].is_01())? sc_lv<1>(): ((cos_basis_fu_817_p0.read()[0].to_bool())? tmp_s_fu_812_p2.read(): tmp_reg_1239.read());
}

void sin_or_cos_double_s::thread_expv_op_fu_306_p2() {
    expv_op_fu_306_p2 = (!ap_const_lv11_44D.is_01() || !loc_V_fu_286_p4.read().is_01())? sc_lv<11>(): (sc_bigint<11>(ap_const_lv11_44D) + sc_biguint<11>(loc_V_fu_286_p4.read()));
}

void sin_or_cos_double_s::thread_fourth_order_double_4_address0() {
    fourth_order_double_4_address0 =  (sc_lv<8>) (tmp_30_i_reg_1257.read());
}

void sin_or_cos_double_s::thread_fourth_order_double_4_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        fourth_order_double_4_ce0 = ap_const_logic_1;
    } else {
        fourth_order_double_4_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_fourth_order_double_5_address0() {
    fourth_order_double_5_address0 =  (sc_lv<8>) (tmp_30_i_fu_645_p1.read());
}

void sin_or_cos_double_s::thread_fourth_order_double_5_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        fourth_order_double_5_ce0 = ap_const_logic_1;
    } else {
        fourth_order_double_5_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_fourth_order_double_6_address0() {
    fourth_order_double_6_address0 =  (sc_lv<8>) (tmp_30_i_fu_645_p1.read());
}

void sin_or_cos_double_s::thread_fourth_order_double_6_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        fourth_order_double_6_ce0 = ap_const_logic_1;
    } else {
        fourth_order_double_6_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_fourth_order_double_7_address0() {
    fourth_order_double_7_address0 =  (sc_lv<8>) (tmp_30_i_reg_1257.read());
}

void sin_or_cos_double_s::thread_fourth_order_double_7_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        fourth_order_double_7_ce0 = ap_const_logic_1;
    } else {
        fourth_order_double_7_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_fourth_order_double_s_address0() {
    fourth_order_double_s_address0 =  (sc_lv<8>) (tmp_30_i_reg_1257.read());
}

void sin_or_cos_double_s::thread_fourth_order_double_s_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        fourth_order_double_s_ce0 = ap_const_logic_1;
    } else {
        fourth_order_double_s_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_grp_fu_372_p0() {
    grp_fu_372_p0 =  (sc_lv<170>) (grp_fu_372_p00.read());
}

void sin_or_cos_double_s::thread_grp_fu_372_p00() {
    grp_fu_372_p00 = esl_zext<223,170>(ret_V_reg_1137.read());
}

void sin_or_cos_double_s::thread_grp_fu_372_p1() {
    grp_fu_372_p1 =  (sc_lv<53>) (grp_fu_372_p10.read());
}

void sin_or_cos_double_s::thread_grp_fu_372_p10() {
    grp_fu_372_p10 = esl_zext<223,53>(p_Result_20_fu_358_p3.read());
}

void sin_or_cos_double_s::thread_grp_fu_620_p0() {
    grp_fu_620_p0 =  (sc_lv<49>) (OP1_V_fu_617_p1.read());
}

void sin_or_cos_double_s::thread_grp_fu_620_p1() {
    grp_fu_620_p1 =  (sc_lv<49>) (OP1_V_fu_617_p1.read());
}

void sin_or_cos_double_s::thread_grp_fu_664_p0() {
    grp_fu_664_p0 =  (sc_lv<49>) (OP2_V_fu_661_p1.read());
}

void sin_or_cos_double_s::thread_grp_fu_664_p1() {
    grp_fu_664_p1 =  (sc_lv<49>) (OP1_V_reg_1245.read());
}

void sin_or_cos_double_s::thread_grp_fu_669_p0() {
    grp_fu_669_p0 =  (sc_lv<49>) (OP2_V_fu_661_p1.read());
}

void sin_or_cos_double_s::thread_grp_fu_669_p1() {
    grp_fu_669_p1 =  (sc_lv<49>) (OP2_V_fu_661_p1.read());
}

void sin_or_cos_double_s::thread_grp_fu_681_p0() {
    grp_fu_681_p0 =  (sc_lv<56>) (grp_fu_681_p00.read());
}

void sin_or_cos_double_s::thread_grp_fu_681_p00() {
    grp_fu_681_p00 = esl_zext<108,56>(p_Val2_15_reg_1223.read());
}

void sin_or_cos_double_s::thread_grp_fu_693_p0() {
    grp_fu_693_p0 =  (sc_lv<49>) (grp_fu_693_p00.read());
}

void sin_or_cos_double_s::thread_grp_fu_693_p00() {
    grp_fu_693_p00 = esl_zext<93,49>(tmp_25_i_reg_1274.read());
}

void sin_or_cos_double_s::thread_grp_fu_752_p0() {
    grp_fu_752_p0 =  (sc_lv<42>) (grp_fu_752_p00.read());
}

void sin_or_cos_double_s::thread_grp_fu_752_p00() {
    grp_fu_752_p00 = esl_zext<75,42>(tmp_27_i_reg_1332.read());
}

void sin_or_cos_double_s::thread_grp_fu_752_p1() {
    grp_fu_752_p1 =  (sc_lv<33>) (grp_fu_752_p10.read());
}

void sin_or_cos_double_s::thread_grp_fu_752_p10() {
    grp_fu_752_p10 = esl_zext<75,33>(fourth_order_double_14_reg_1357.read());
}

void sin_or_cos_double_s::thread_grp_fu_853_p1() {
    grp_fu_853_p1 =  (sc_lv<63>) (grp_fu_853_p10.read());
}

void sin_or_cos_double_s::thread_grp_fu_853_p10() {
    grp_fu_853_p10 = esl_zext<126,63>(Mx_V_read_assign_fu_840_p3.read());
}

void sin_or_cos_double_s::thread_grp_scaled_fixed2ieee_fu_268_ap_start() {
    grp_scaled_fixed2ieee_fu_268_ap_start = grp_scaled_fixed2ieee_fu_268_ap_start_reg.read();
}

void sin_or_cos_double_s::thread_loc_V_1_fu_296_p1() {
    loc_V_1_fu_296_p1 = p_Val2_s_fu_274_p1.read().range(52-1, 0);
}

void sin_or_cos_double_s::thread_loc_V_2_fu_898_p4() {
    loc_V_2_fu_898_p4 = p_Val2_25_fu_887_p1.read().range(62, 52);
}

void sin_or_cos_double_s::thread_loc_V_3_fu_908_p1() {
    loc_V_3_fu_908_p1 = p_Val2_25_fu_887_p1.read().range(52-1, 0);
}

void sin_or_cos_double_s::thread_loc_V_fu_286_p4() {
    loc_V_fu_286_p4 = p_Val2_s_fu_274_p1.read().range(62, 52);
}

void sin_or_cos_double_s::thread_not_do_cos_i_fu_626_p0() {
    not_do_cos_i_fu_626_p0 =  (sc_lv<1>) (do_cos.read());
}

void sin_or_cos_double_s::thread_not_do_cos_i_fu_626_p2() {
    not_do_cos_i_fu_626_p2 = (not_do_cos_i_fu_626_p0.read() ^ ap_const_lv1_1);
}

void sin_or_cos_double_s::thread_not_or_cond_demorgan_fu_1057_p2() {
    not_or_cond_demorgan_fu_1057_p2 = (tmp_6_reg_1204.read() & tmp_7_reg_1152.read());
}

void sin_or_cos_double_s::thread_not_or_cond_fu_1061_p2() {
    not_or_cond_fu_1061_p2 = (not_or_cond_demorgan_fu_1057_p2.read() ^ ap_const_lv1_1);
}

void sin_or_cos_double_s::thread_not_tmp_s_fu_1016_p2() {
    not_tmp_s_fu_1016_p2 = (tmp_8_reg_1210.read() ^ ap_const_lv1_1);
}

void sin_or_cos_double_s::thread_or_cond_fu_1001_p2() {
    or_cond_fu_1001_p2 = (tmp_6_reg_1204.read() & tmp_7_reg_1152.read());
}

void sin_or_cos_double_s::thread_p_Ex_V_ret_fu_859_p3() {
    p_Ex_V_ret_fu_859_p3 = (!cos_basis_reg_1392.read()[0].is_01())? sc_lv<11>(): ((cos_basis_reg_1392.read()[0].to_bool())? ap_const_lv11_0: Ex_V_reg_1192.read());
}

void sin_or_cos_double_s::thread_p_Result_1_cast_fu_1067_p3() {
    p_Result_1_cast_fu_1067_p3 = (!not_or_cond_fu_1061_p2.read()[0].is_01())? sc_lv<52>(): ((not_or_cond_fu_1061_p2.read()[0].to_bool())? ap_const_lv52_FFFFFFFFFFFFF: ap_const_lv52_0);
}

void sin_or_cos_double_s::thread_p_Result_20_fu_358_p3() {
    p_Result_20_fu_358_p3 = esl_concat<1,52>(ap_const_lv1_1, loc_V_1_reg_1115.read());
}

void sin_or_cos_double_s::thread_p_Result_21_fu_447_p3() {
    p_Result_21_fu_447_p3 = esl_concat<61,1>(p_Result_i2_i_reg_1180.read(), ap_const_lv1_1);
}

void sin_or_cos_double_s::thread_p_Result_22_fu_454_p4() {
    p_Result_22_fu_454_p4 = p_Result_21_fu_447_p3.read().range(0, 61);
}

void sin_or_cos_double_s::thread_p_Result_23_fu_464_p3() {
    p_Result_23_fu_464_p3 = esl_concat<2,62>(ap_const_lv2_3, p_Result_22_fu_454_p4.read());
}

void sin_or_cos_double_s::thread_p_Result_24_fu_638_p3() {
    p_Result_24_fu_638_p3 = esl_concat<1,7>(sin_basis_fu_632_p2.read(), p_Result_i_reg_1218.read());
}

void sin_or_cos_double_s::thread_p_Result_25_fu_890_p3() {
    p_Result_25_fu_890_p3 = p_Val2_25_fu_887_p1.read().range(63, 63);
}

void sin_or_cos_double_s::thread_p_Result_26_fu_912_p3() {
    p_Result_26_fu_912_p3 = esl_concat<1,3>(p_Result_19_reg_1102.read(), p_Val2_29_reg_1169.read());
}

void sin_or_cos_double_s::thread_p_Result_27_fu_1088_p4() {
    p_Result_27_fu_1088_p4 = esl_concat<12,52>(esl_concat<1,11>(p_Result_s_41_fu_1041_p3.read(), ret_V_6_fu_1049_p3.read()), ret_V_7_fu_1080_p3.read());
}

void sin_or_cos_double_s::thread_p_Result_i_i_fu_320_p4() {
    p_Result_i_i_fu_320_p4 = addr_V_fu_312_p3.read().range(10, 7);
}

void sin_or_cos_double_s::thread_p_Result_s_39_fu_1026_p3() {
    p_Result_s_39_fu_1026_p3 = (!tmp_9_fu_1021_p2.read()[0].is_01())? sc_lv<1>(): ((tmp_9_fu_1021_p2.read()[0].to_bool())? not_tmp_s_fu_1016_p2.read(): p_Result_25_fu_890_p3.read());
}

void sin_or_cos_double_s::thread_p_Result_s_40_fu_1034_p3() {
    p_Result_s_40_fu_1034_p3 = (!tmp_8_reg_1210.read()[0].is_01())? sc_lv<11>(): ((tmp_8_reg_1210.read()[0].to_bool())? ap_const_lv11_7FF: loc_V_2_fu_898_p4.read());
}

void sin_or_cos_double_s::thread_p_Result_s_41_fu_1041_p3() {
    p_Result_s_41_fu_1041_p3 = (!or_cond_fu_1001_p2.read()[0].is_01())? sc_lv<1>(): ((or_cond_fu_1001_p2.read()[0].to_bool())? p_Result_s_fu_1005_p2.read(): p_Result_s_39_fu_1026_p3.read());
}

void sin_or_cos_double_s::thread_p_Result_s_fu_1005_p2() {
    p_Result_s_fu_1005_p2 = (p_Result_19_reg_1102.read() & not_do_cos_i_reg_1252.read());
}

void sin_or_cos_double_s::thread_p_Val2_11_fu_418_p3() {
    p_Val2_11_fu_418_p3 = (!tmp_14_fu_409_p1.read()[0].is_01())? sc_lv<124>(): ((tmp_14_fu_409_p1.read()[0].to_bool())? p_Val2_i_fu_413_p2.read(): p_Val2_8_reg_1158.read());
}

void sin_or_cos_double_s::thread_p_Val2_13_fu_488_p2() {
    p_Val2_13_fu_488_p2 = (!tmp_15_i_fu_484_p1.read().is_01())? sc_lv<124>(): p_Val2_11_reg_1175.read() << (unsigned short)tmp_15_i_fu_484_p1.read().to_uint();
}

void sin_or_cos_double_s::thread_p_Val2_14_fu_565_p3() {
    p_Val2_14_fu_565_p3 = (!isNeg_reg_1198.read()[0].is_01())? sc_lv<63>(): ((isNeg_reg_1198.read()[0].to_bool())? tmp_22_i_fu_555_p2.read(): tmp_23_i_fu_560_p2.read());
}

void sin_or_cos_double_s::thread_p_Val2_15_fu_582_p1() {
    p_Val2_15_fu_582_p1 = p_Val2_14_fu_565_p3.read().range(56-1, 0);
}

void sin_or_cos_double_s::thread_p_Val2_20_fu_739_p3() {
    p_Val2_20_fu_739_p3 = esl_concat<59,4>(p_Val2_19_reg_1342.read(), ap_const_lv4_0);
}

void sin_or_cos_double_s::thread_p_Val2_21_fu_787_p2() {
    p_Val2_21_fu_787_p2 = (!tmp_32_i_fu_780_p1.read().is_01() || !tmp_33_i_fu_784_p1.read().is_01())? sc_lv<64>(): (sc_bigint<64>(tmp_32_i_fu_780_p1.read()) + sc_bigint<64>(tmp_33_i_fu_784_p1.read()));
}

void sin_or_cos_double_s::thread_p_Val2_22_fu_796_p2() {
    p_Val2_22_fu_796_p2 = (!p_Val2_21_fu_787_p2.read().is_01() || !tmp_35_i_cast_fu_793_p1.read().is_01())? sc_lv<64>(): (sc_biguint<64>(p_Val2_21_fu_787_p2.read()) + sc_bigint<64>(tmp_35_i_cast_fu_793_p1.read()));
}

void sin_or_cos_double_s::thread_p_Val2_23_fu_826_p2() {
    p_Val2_23_fu_826_p2 = (!p_Val2_22_reg_1382.read().is_01() || !tmp_37_i_cast_fu_823_p1.read().is_01())? sc_lv<64>(): (sc_biguint<64>(p_Val2_22_reg_1382.read()) + sc_biguint<64>(tmp_37_i_cast_fu_823_p1.read()));
}

void sin_or_cos_double_s::thread_p_Val2_25_fu_887_p1() {
    p_Val2_25_fu_887_p1 = resultf_reg_1424.read();
}

void sin_or_cos_double_s::thread_p_Val2_29_fu_403_p3() {
    p_Val2_29_fu_403_p3 = (!closepath_reg_1121.read()[0].is_01())? sc_lv<3>(): ((closepath_reg_1121.read()[0].to_bool())? ap_const_lv3_0: tmp_14_i_reg_1164.read());
}

void sin_or_cos_double_s::thread_p_Val2_4_fu_764_p0() {
    p_Val2_4_fu_764_p0 =  (sc_lv<35>) (p_Val2_4_fu_764_p00.read());
}

void sin_or_cos_double_s::thread_p_Val2_4_fu_764_p00() {
    p_Val2_4_fu_764_p00 = esl_zext<60,35>(tmp_29_i_reg_1337.read());
}

void sin_or_cos_double_s::thread_p_Val2_4_fu_764_p1() {
    p_Val2_4_fu_764_p1 =  (sc_lv<25>) (p_Val2_4_fu_764_p10.read());
}

void sin_or_cos_double_s::thread_p_Val2_4_fu_764_p10() {
    p_Val2_4_fu_764_p10 = esl_zext<60,25>(fourth_order_double_16_reg_1362.read());
}

void sin_or_cos_double_s::thread_p_Val2_4_fu_764_p2() {
    p_Val2_4_fu_764_p2 = (!p_Val2_4_fu_764_p0.read().is_01() || !p_Val2_4_fu_764_p1.read().is_01())? sc_lv<60>(): sc_biguint<35>(p_Val2_4_fu_764_p0.read()) * sc_biguint<25>(p_Val2_4_fu_764_p1.read());
}

void sin_or_cos_double_s::thread_p_Val2_i_fu_413_p2() {
    p_Val2_i_fu_413_p2 = (!ap_const_lv124_0.is_01() || !p_Val2_8_reg_1158.read().is_01())? sc_lv<124>(): (sc_biguint<124>(ap_const_lv124_0) - sc_biguint<124>(p_Val2_8_reg_1158.read()));
}

void sin_or_cos_double_s::thread_p_Val2_s_fu_274_p1() {
    p_Val2_s_fu_274_p1 = t_in.read();
}

void sin_or_cos_double_s::thread_p_cast_cast_fu_1009_p0() {
    p_cast_cast_fu_1009_p0 =  (sc_lv<1>) (do_cos.read());
}

void sin_or_cos_double_s::thread_p_cast_cast_fu_1009_p3() {
    p_cast_cast_fu_1009_p3 = (!p_cast_cast_fu_1009_p0.read()[0].is_01())? sc_lv<11>(): ((p_cast_cast_fu_1009_p0.read()[0].to_bool())? ap_const_lv11_3FF: ap_const_lv11_0);
}

void sin_or_cos_double_s::thread_r_V_3_fu_834_p2() {
    r_V_3_fu_834_p2 = (!p_Val2_23_fu_826_p2.read().is_01() || !tmp_39_i_cast_fu_831_p1.read().is_01())? sc_lv<64>(): (sc_biguint<64>(p_Val2_23_fu_826_p2.read()) + sc_biguint<64>(tmp_39_i_cast_fu_831_p1.read()));
}

void sin_or_cos_double_s::thread_r_V_4_fu_342_p2() {
    r_V_4_fu_342_p2 = (!tmp_4_i_i_fu_339_p1.read().is_01())? sc_lv<256>(): ref_4oPi_table_256_V_q0.read() << (unsigned short)tmp_4_i_i_fu_339_p1.read().to_uint();
}

void sin_or_cos_double_s::thread_r_V_fu_880_p2() {
    r_V_fu_880_p2 = (!ap_const_lv12_0.is_01() || !rhs_V_fu_876_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_0) - sc_bigint<12>(rhs_V_fu_876_p1.read()));
}

void sin_or_cos_double_s::thread_ref_4oPi_table_256_V_address0() {
    ref_4oPi_table_256_V_address0 =  (sc_lv<4>) (tmp_2_i_i_fu_330_p1.read());
}

void sin_or_cos_double_s::thread_ref_4oPi_table_256_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ref_4oPi_table_256_V_ce0 = ap_const_logic_1;
    } else {
        ref_4oPi_table_256_V_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_ret_V_6_fu_1049_p3() {
    ret_V_6_fu_1049_p3 = (!or_cond_fu_1001_p2.read()[0].is_01())? sc_lv<11>(): ((or_cond_fu_1001_p2.read()[0].to_bool())? p_cast_cast_fu_1009_p3.read(): p_Result_s_40_fu_1034_p3.read());
}

void sin_or_cos_double_s::thread_ret_V_7_fu_1080_p3() {
    ret_V_7_fu_1080_p3 = (!tmp_10_fu_1075_p2.read()[0].is_01())? sc_lv<52>(): ((tmp_10_fu_1075_p2.read()[0].to_bool())? p_Result_1_cast_fu_1067_p3.read(): loc_V_3_fu_908_p1.read());
}

void sin_or_cos_double_s::thread_rhs_V_fu_876_p1() {
    rhs_V_fu_876_p1 = esl_sext<12,11>(p_Ex_V_ret_fu_859_p3.read());
}

void sin_or_cos_double_s::thread_sh_assign_2_cast_fu_547_p1() {
    sh_assign_2_cast_fu_547_p1 = esl_sext<32,12>(sh_assign_fu_540_p3.read());
}

void sin_or_cos_double_s::thread_sh_assign_fu_540_p3() {
    sh_assign_fu_540_p3 = (!isNeg_reg_1198.read()[0].is_01())? sc_lv<12>(): ((isNeg_reg_1198.read()[0].to_bool())? tmp_20_i_fu_534_p2.read(): sh_cast_fu_531_p1.read());
}

void sin_or_cos_double_s::thread_sh_cast_fu_531_p1() {
    sh_cast_fu_531_p1 = esl_sext<12,11>(Ex_V_reg_1192.read());
}

void sin_or_cos_double_s::thread_sin_basis_fu_632_p2() {
    sin_basis_fu_632_p2 = (tmp_fu_596_p10.read() ^ not_do_cos_i_fu_626_p2.read());
}

void sin_or_cos_double_s::thread_storemerge_i_fu_440_p3() {
    storemerge_i_fu_440_p3 = (!closepath_reg_1121.read()[0].is_01())? sc_lv<11>(): ((closepath_reg_1121.read()[0].to_bool())? tmp_i_fu_435_p2.read(): ap_const_lv11_0);
}

void sin_or_cos_double_s::thread_tmp_10_fu_1075_p2() {
    tmp_10_fu_1075_p2 = (or_cond_fu_1001_p2.read() | tmp_8_reg_1210.read());
}

void sin_or_cos_double_s::thread_tmp_13_fu_335_p1() {
    tmp_13_fu_335_p1 = addr_V_fu_312_p3.read().range(7-1, 0);
}

void sin_or_cos_double_s::thread_tmp_14_fu_409_p1() {
    tmp_14_fu_409_p1 = p_Val2_29_fu_403_p3.read().range(1-1, 0);
}

void sin_or_cos_double_s::thread_tmp_15_i_fu_484_p1() {
    tmp_15_i_fu_484_p1 = esl_zext<124,6>(Mx_zeros_V_fu_480_p1.read());
}

void sin_or_cos_double_s::thread_tmp_18_i_fu_503_p1() {
    tmp_18_i_fu_503_p1 = esl_zext<11,6>(Mx_zeros_V_fu_480_p1.read());
}

void sin_or_cos_double_s::thread_tmp_20_i_fu_534_p2() {
    tmp_20_i_fu_534_p2 = (!ap_const_lv12_0.is_01() || !sh_cast_fu_531_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_0) - sc_bigint<12>(sh_cast_fu_531_p1.read()));
}

void sin_or_cos_double_s::thread_tmp_21_i_fu_551_p1() {
    tmp_21_i_fu_551_p1 = esl_zext<63,32>(sh_assign_2_cast_fu_547_p1.read());
}

void sin_or_cos_double_s::thread_tmp_22_i_fu_555_p2() {
    tmp_22_i_fu_555_p2 = (!tmp_21_i_fu_551_p1.read().is_01())? sc_lv<63>(): Mx_V_reg_1185.read() >> (unsigned short)tmp_21_i_fu_551_p1.read().to_uint();
}

void sin_or_cos_double_s::thread_tmp_23_i_fu_560_p2() {
    tmp_23_i_fu_560_p2 = (!tmp_21_i_fu_551_p1.read().is_01())? sc_lv<63>(): Mx_V_reg_1185.read() << (unsigned short)tmp_21_i_fu_551_p1.read().to_uint();
}

void sin_or_cos_double_s::thread_tmp_2_i_i_fu_330_p1() {
    tmp_2_i_i_fu_330_p1 = esl_zext<64,4>(p_Result_i_i_fu_320_p4.read());
}

void sin_or_cos_double_s::thread_tmp_30_i_fu_645_p1() {
    tmp_30_i_fu_645_p1 = esl_zext<64,8>(p_Result_24_fu_638_p3.read());
}

void sin_or_cos_double_s::thread_tmp_32_i_fu_780_p1() {
    tmp_32_i_fu_780_p1 = esl_sext<64,63>(p_Val2_20_fu_739_p3.read());
}

void sin_or_cos_double_s::thread_tmp_33_i_fu_784_p1() {
    tmp_33_i_fu_784_p1 = esl_sext<64,56>(tmp_12_i_reg_1347.read());
}

void sin_or_cos_double_s::thread_tmp_35_i_cast_fu_793_p1() {
    tmp_35_i_cast_fu_793_p1 = esl_sext<64,48>(tmp_14_i1_reg_1352.read());
}

void sin_or_cos_double_s::thread_tmp_37_i_cast_fu_823_p1() {
    tmp_37_i_cast_fu_823_p1 = esl_zext<64,37>(tmp_1_reg_1387.read());
}

void sin_or_cos_double_s::thread_tmp_39_i_cast_fu_831_p1() {
    tmp_39_i_cast_fu_831_p1 = esl_zext<64,29>(tmp_2_reg_1377.read());
}

void sin_or_cos_double_s::thread_tmp_4_i_i_fu_339_p1() {
    tmp_4_i_i_fu_339_p1 = esl_zext<256,7>(tmp_13_reg_1132.read());
}

void sin_or_cos_double_s::thread_tmp_5_fu_994_p3() {
    tmp_5_fu_994_p3 = (!cos_basis_reg_1392.read()[0].is_01())? sc_lv<1>(): ((cos_basis_reg_1392.read()[0].to_bool())? tmp_3_fu_918_p18.read(): tmp_4_fu_956_p18.read());
}

void sin_or_cos_double_s::thread_tmp_6_fu_521_p2() {
    tmp_6_fu_521_p2 = (!loc_V_reg_1108.read().is_01() || !ap_const_lv11_0.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_reg_1108.read() == ap_const_lv11_0);
}

void sin_or_cos_double_s::thread_tmp_7_fu_378_p2() {
    tmp_7_fu_378_p2 = (!loc_V_1_reg_1115.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_1_reg_1115.read() == ap_const_lv52_0);
}

void sin_or_cos_double_s::thread_tmp_8_fu_526_p2() {
    tmp_8_fu_526_p2 = (!loc_V_reg_1108.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_reg_1108.read() == ap_const_lv11_7FF);
}

void sin_or_cos_double_s::thread_tmp_9_fu_1021_p2() {
    tmp_9_fu_1021_p2 = (tmp_8_reg_1210.read() | tmp_5_fu_994_p3.read());
}

void sin_or_cos_double_s::thread_tmp_i3_i_fu_472_p3() {
    tmp_i3_i_fu_472_p3 = esl_cttz<64,64>(p_Result_23_fu_464_p3.read());
}

void sin_or_cos_double_s::thread_tmp_i_fu_435_p2() {
    tmp_i_fu_435_p2 = (!ap_const_lv11_403.is_01() || !loc_V_reg_1108.read().is_01())? sc_lv<11>(): (sc_bigint<11>(ap_const_lv11_403) + sc_biguint<11>(loc_V_reg_1108.read()));
}

void sin_or_cos_double_s::thread_tmp_s_fu_812_p2() {
    tmp_s_fu_812_p2 = (tmp_reg_1239.read() ^ ap_const_lv1_1);
}

void sin_or_cos_double_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            if ((esl_seteq<1,1,1>(grp_scaled_fixed2ieee_fu_268_ap_done.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()))) {
                ap_NS_fsm = ap_ST_fsm_state24;
            } else {
                ap_NS_fsm = ap_ST_fsm_state23;
            }
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXXXXXXXXXX";
            break;
    }
}

}

